RAW_CREATED_TYPE = 'created'
RAW_UPDATED_TYPE = 'updated'
RAW_DELETED_TYPE = 'deleted'
RAW_IGNORED_TYPE = 'ignored'

RAW_TYPE_CONFIG = (
    (RAW_CREATED_TYPE, RAW_CREATED_TYPE),
    (RAW_UPDATED_TYPE, RAW_UPDATED_TYPE),
    (RAW_DELETED_TYPE, RAW_DELETED_TYPE),
    (RAW_IGNORED_TYPE, RAW_IGNORED_TYPE)
)
