# Generated by Django 3.1.14 on 2023-02-24 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_better_admin_arrayfield.models.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthTokenRequest',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=250)),
                ('spapi_oauth_code', models.CharField(max_length=250)),
                ('selling_partner_id', models.CharField(max_length=250)),
                ('status_code', models.IntegerField(default=400)),
                ('payload', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('aws_oauth_consent_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('aws_oauth_access_token_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('aws_oauth_refresh_token_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('web_aws_oauth_redirect', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('api_aws_oauth_redirect', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('aws_access_key_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('aws_secret_access_key', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('aws_default_region', models.CharField(max_length=255)),
                ('aws_role_arn', models.CharField(max_length=255)),
                ('spapi_app_id', models.CharField(max_length=255)),
                ('amz_lwa_client_id', models.CharField(max_length=255)),
                ('amz_lwa_client_secret', models.CharField(max_length=255)),
                ('max_report_retry', models.IntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SPReportCategory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sort', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='selling_partner.spreportcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SPReportType',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255, unique=True)),
                ('sort', models.IntegerField(default=0)),
                ('note', models.TextField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_types', to='selling_partner.spreportcategory')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='SPReportClient',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ac_report_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('batch_ids', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255, unique=True), blank=True, default=list, size=None)),
                ('date_range_covered_start', models.DateField(blank=True, default=None, null=True)),
                ('date_range_covered_end', models.DateField(blank=True, default=None, null=True)),
                ('date_requested', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_completed', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Ready', 'Ready'), ('Cancelled', 'Cancelled'), ('Error', 'Error')], default='In Progress', max_length=255)),
                ('file_names', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500, unique=True), blank=True, default=list, size=None)),
                ('download_urls', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500, unique=True), blank=True, default=list, size=None)),
                ('log', models.TextField(blank=True, default=None, null=True)),
                ('msg_error', models.JSONField(default=dict)),
                ('retry', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.channel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.user')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selling_partner.spreporttype')),
            ],
        ),
        migrations.CreateModel(
            name='SPOauthClientRegister',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latest', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal')),
                ('oauth_token_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selling_partner.oauthtokenrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='oauthtokenrequest',
            index=models.Index(fields=['selling_partner_id', 'spapi_oauth_code', 'state'], name='selling_par_selling_bc3c45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='oauthtokenrequest',
            unique_together={('state', 'spapi_oauth_code', 'selling_partner_id')},
        ),
        migrations.AddIndex(
            model_name='spreportclient',
            index=models.Index(fields=['client', 'channel', 'report_type', 'status'], name='selling_par_client__6013b9_idx'),
        ),
        migrations.AddIndex(
            model_name='spreportclient',
            index=models.Index(fields=['client', 'channel', 'report_type', 'date_range_covered_start', 'date_range_covered_end'], name='selling_par_client__4b3ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='spreportclient',
            index=models.Index(fields=['client', 'channel', 'report_type', 'date_requested'], name='selling_par_client__75fac3_idx'),
        ),
        migrations.AddIndex(
            model_name='spreportclient',
            index=models.Index(fields=['client', 'channel', 'report_type', 'date_completed'], name='selling_par_client__19b3da_idx'),
        ),
        migrations.AddIndex(
            model_name='spreportclient',
            index=models.Index(fields=['client', 'channel', 'report_type', 'creator'], name='selling_par_client__1f92a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='spreportclient',
            constraint=models.UniqueConstraint(condition=models.Q(('date_range_covered_end__isnull', False), ('date_range_covered_start__isnull', False), ('status__in', ['In Progress', 'Ready'])), fields=('client', 'channel', 'report_type', 'date_range_covered_start', 'date_range_covered_end'), name='unique_date_range_covered_is_not_null'),
        ),
        migrations.AddConstraint(
            model_name='spreportclient',
            constraint=models.UniqueConstraint(condition=models.Q(('date_range_covered_end__isnull', True), ('date_range_covered_start__isnull', True), ('status__in', ['In Progress'])), fields=('client', 'channel', 'report_type'), name='unique_date_range_covered_is_null'),
        ),
        migrations.AlterUniqueTogether(
            name='spreportcategory',
            unique_together={('parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='spoauthclientregister',
            index=models.Index(fields=['client', 'oauth_token_request'], name='selling_par_client__e006a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spoauthclientregister',
            unique_together={('client', 'oauth_token_request')},
        ),
    ]
