# Generated by Django 3.1.14 on 2023-03-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreporttype',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='spreporttype',
            unique_together={('category', 'name', 'value')},
        ),
    ]
