# Generated by Django 3.1.14 on 2023-03-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_partner', '0002_auto_20230315_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreportcategory',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spreporttype',
            name='is_date_range',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spreporttype',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='spreportcategory',
            unique_together={('parent', 'value')},
        ),
    ]
