# Generated by Django 3.1.14 on 2023-09-19 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_auto_20230829_0344'),
        ('selling_partner', '0003_auto_20230316_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreportclient',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='spreporttype',
            name='source',
            field=models.CharField(choices=[('SPAPI', 'Selling Partner API'), ('LOCAL', 'Local System')], default='SPAPI', max_length=255),
        ),
        migrations.AlterField(
            model_name='spreportclient',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.user'),
        ),
    ]
