# Generated by Django 3.1.14 on 2024-11-28 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0036_auto_20241128_0743'),
        ('selling_partner', '0004_auto_20230919_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoauthclientregister',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.user'),
        ),
    ]
