# Generated by Django 3.1.14 on 2025-05-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling_partner', '0005_spoauthclientregister_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='amz_lwa_expired',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
