# Generated by Django 3.1.14 on 2025-05-16 04:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('selling_partner', '0006_setting_amz_lwa_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='amz_lwa_client_id',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='amz_lwa_client_secret',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='amz_lwa_expired',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='aws_access_key_id',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='aws_default_region',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='aws_role_arn',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='aws_secret_access_key',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='spapi_app_id',
        ),
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spapi_app_id', models.CharField(max_length=255, unique=True)),
                ('aws_access_key_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('aws_secret_access_key', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('aws_default_region', models.CharField(max_length=255)),
                ('aws_role_arn', models.CharField(max_length=255)),
                ('amz_lwa_client_id', models.CharField(max_length=255)),
                ('amz_lwa_client_secret', models.CharField(max_length=255)),
                ('amz_lwa_expired', models.DateTimeField(blank=True, default=None, null=True)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selling_partner.setting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='spoauthclientregister',
            name='app_setting',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='selling_partner.appsetting'),
        ),
    ]
