# Generated by Django 3.1.14 on 2023-05-24 10:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0008_auto_20230524_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField()),
                ('is_healthy', models.BooleanField()),
                ('service_name', models.CharField(max_length=50, unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['service_name'],
            },
        ),
        migrations.CreateModel(
            name='StatReport',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_time_control', models.JSONField(default=dict)),
                ('sales_time_control', models.JSONField(default=dict)),
                ('financial_event_time_control', models.JSONField(default=dict)),
                ('informed_time_control', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatClientChannelReport',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=50)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('total_sales', models.IntegerField(default=0)),
                ('total_time_control', models.IntegerField(default=0)),
                ('total_time_control_completed', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.channel')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrgClientHealth',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField()),
                ('is_healthy', models.BooleanField()),
                ('service_name', models.CharField(max_length=50)),
                ('message', models.JSONField(default=dict)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='statclientchannelreport',
            index=models.Index(fields=['organization', 'client', 'channel', 'total_time_control', 'total_time_control_completed'], name='stat_report_organiz_bb7300_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='statclientchannelreport',
            unique_together={('organization', 'client', 'channel', 'report_type', 'report_date')},
        ),
        migrations.AddIndex(
            model_name='orgclienthealth',
            index=models.Index(fields=['organization', 'client', 'service_name', 'is_healthy', 'is_enabled'], name='stat_report_organiz_c762bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orgclienthealth',
            unique_together={('organization', 'client', 'service_name')},
        ),
    ]
