# Generated by Django 3.1.14 on 2023-06-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_report', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Health',
        ),
    ]
