# Generated by Django 3.1.14 on 2023-07-31 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0010_auto_20230725_0403'),
        ('stat_report', '0002_delete_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statclientchannelreport',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='statclientchannelreport',
            name='report_type',
            field=models.CharField(choices=[('hour', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=50),
        ),
        migrations.CreateModel(
            name='StatSaleRecentReport',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('hour', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='hour', max_length=50)),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_sales_affected', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.channel')),
            ],
            options={
                'unique_together': {('channel', 'report_type', 'report_date')},
            },
        ),
    ]
