# Generated by Django 3.1.14 on 2023-08-10 03:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0011_delete_clientreportcost'),
        ('stat_report', '0003_auto_20230731_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatSaleRecentSummaryReport',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('hour', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='hour', max_length=50)),
                ('total_sales_affected', models.IntegerField(default=0)),
                ('report_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('channel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ClientReportCost',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_sales', models.IntegerField()),
                ('total_30d_sales', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='statsalerecentsummaryreport',
            constraint=models.UniqueConstraint(condition=models.Q(report_date__isnull=True), fields=('channel', 'report_type'), name='unique_stat_sale_marketplace_summary'),
        ),
        migrations.AddConstraint(
            model_name='statsalerecentsummaryreport',
            constraint=models.UniqueConstraint(condition=models.Q(channel__isnull=True), fields=('report_date', 'report_type'), name='unique_stat_sale_report_date_summary'),
        ),
        migrations.AlterUniqueTogether(
            name='clientreportcost',
            unique_together={('client', 'date')},
        ),
    ]
