# Generated by Django 3.1.14 on 2023-10-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_report', '0004_auto_20230810_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='statclientchannelreport',
            name='total_done_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statclientchannelreport',
            name='total_error_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statclientchannelreport',
            name='total_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statsalerecentreport',
            name='total_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statsalerecentreport',
            name='total_jobs_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statsalerecentreport',
            name='total_jobs_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statsalerecentsummaryreport',
            name='total_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statsalerecentsummaryreport',
            name='total_jobs_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statsalerecentsummaryreport',
            name='total_jobs_failed',
            field=models.IntegerField(default=0),
        ),
    ]
