from typing import Union

APP_TRANSIT = "transit"
APP_MWRW = "mwrw"  # noqa
APP_DC = "data_central"

APPLICATION_FOR_STRIPE = ((APP_TRANSIT, "2D Transit"), (APP_MWRW, "MAP Watcher"), (APP_DC, "Data Central"))

APPLICATION = APPLICATION_FOR_STRIPE

PLAN_STANDARD = "STANDARD"
PLAN_INDIVIDUAL = "INDIVIDUAL"
PLAN_PROFESSIONAL = "PROFESSIONAL"
PLAN_BUSINESS = "BUSINESS"
PLAN_ENTERPRISE = "ENTERPRISE"
PLAN_CUSTOM = "CUSTOM"
PLAN_CUSTOM_ON_DEMAND = "DEMAND"

PLAN_TYPE = (
    (PLAN_STANDARD, "Standard"),
    (PLAN_INDIVIDUAL, "Individual"),
    (PLAN_PROFESSIONAL, "Professional"),
    (PLAN_BUSINESS, "Business"),
    (PLAN_ENTERPRISE, "Enterprise"),
    (PLAN_CUSTOM_ON_DEMAND, "Demand"),
    (PLAN_CUSTOM, "Custom"),
)

PERIOD_FOR_STRIPE_CHARGING = (
    ("daily", "Daily"),
    ("weekly", "Weekly"),
    ("monthly", "Monthly"),
    ("3-month", "Every 3 months"),
    ("6-month", "Every 6 months"),
    ("yearly", "Yearly"),
)

ACTIVITY_GRADE_CHANGE = "GRADE_CHANGE"
ACTIVITY_PREVIEW_NEW_PLAN = "PREVIEW_NEW_PLAN"
ACTIVITY_UNSUBSCRIBE = "UNSUBSCRIBE"
ACTIVITY_CHANGE_DEFAULT_PAYMENT = "CHANGE_DEFAULT_PAYMENT"
ACTIVITY_DELETE_PAYMENT_METHOD = "DELETE_PAYMENT_METHOD"

SUBSCRIPTION_ACTIVITY = (
    (ACTIVITY_GRADE_CHANGE, "Grade change"),
    (ACTIVITY_PREVIEW_NEW_PLAN, "Preview new plan"),
    (ACTIVITY_UNSUBSCRIBE, "Unsubscribe"),
    (ACTIVITY_CHANGE_DEFAULT_PAYMENT, "Change default payment"),
    (ACTIVITY_DELETE_PAYMENT_METHOD, "Delete payment method"),
)

SUBSCRIPTION_POST_PAID = "POST_PAID"
SUBSCRIPTION_PRE_PAID = "PRE_PAID"
SUBSCRIPTION_FULL_PACKAGE = "FULL_PACK"

SUBSCRIPTION_MODE = (
    (SUBSCRIPTION_POST_PAID, "Post paid"),
    (SUBSCRIPTION_PRE_PAID, "Pre paid"),
    (SUBSCRIPTION_FULL_PACKAGE, "Fully package"),
)

INVOICE_DRAFT = "DRAFT"
INVOICE_SUCCESS = "SUCCESS"
INVOICE_ERROR = "ERROR"

INVOICE_STATUS = (
    (INVOICE_DRAFT, "Draft"),
    (INVOICE_SUCCESS, "Success"),
    (INVOICE_ERROR, "Error"),
)

INVOICE_ITEM_MONGO_KEY = "MONGO"
INVOICE_ITEM_REDIS_KEY = "REDIS"

INVOICE_ITEM_GROUP = (
    (INVOICE_ITEM_MONGO_KEY, "Mongodb"),
    (INVOICE_ITEM_REDIS_KEY, "Redis"),
)

BALANCE_SYSTEM_UNIT = "SYSTEM_UNIT"
BALANCE_CURRENCY_UNIT = "CURRENCY_UNIT"

BALANCE_TYPE = (
    (BALANCE_SYSTEM_UNIT, "System unit"),
    (BALANCE_CURRENCY_UNIT, "Currency unit"),
)

TRANSACTION_TYPE_RECURRING_CHARGE = "RECURRING_CHARGE"
TRANSACTION_TYPE_CHANGING_SUBSCRIPTION = "CHANGING_SUBSCRIPTION"
TRANSACTION_TYPE_ADMIN = "SYSTEM_ADMIN_ADD"
TRANSACTION_TYPE_USER_PURCHASE = "USER_PURCHASE"
TRANSACTION_TYPE_CREDIT_USAGE = "CREDIT_USAGE"
TRANSACTION_TYPE_SERVICE = "SERVICE_SUBMISSION"
TRANSACTION_TYPE_MW = "SERVICE_MW_SUBMISSION"

TRANSACTION_TYPE = (
    (TRANSACTION_TYPE_RECURRING_CHARGE, "Recurring charge from subscription"),
    (TRANSACTION_TYPE_CHANGING_SUBSCRIPTION, "Changing subscription"),
    (TRANSACTION_TYPE_ADMIN, "Adding by system admin"),
    (TRANSACTION_TYPE_USER_PURCHASE, "User purchase"),
    (TRANSACTION_TYPE_CREDIT_USAGE, "Credit usage"),
    (TRANSACTION_TYPE_SERVICE, "Service submission"),
    (TRANSACTION_TYPE_MW, "Service MW submission"),
)

"""
STRIPE
Coupon duration mode
"""
DURATION_TYPE_ONCE = "once"
DURATION_TYPE_FOREVER = "forever"
DURATION_TYPE_MONTHS = "repeating"
#
COUPON_DURATION_MODE = (
    (DURATION_TYPE_ONCE, "Once"),
    (DURATION_TYPE_FOREVER, "Forever"),
    (DURATION_TYPE_MONTHS, "Repeating")
)


def get_transaction_type_name(key: str) -> Union[str, None]:
    find_one = filter(lambda ele: ele[0] == key, TRANSACTION_TYPE)
    try:
        res = next(find_one)
        return res[1]
    except StopIteration:
        return None


STRIPE_CHECKOUT_SUBSCRIPTION = "CHECKOUT_SUBSCRIPTION"
STRIPE_CHECKOUT_FUND = "CHECKOUT_FUND"

WARNING_LOW_BALANCE = 10000
