IN_PROGRESS_STATUS = "In Progress"
READY_STATUS = "Ready"
CANCELLED_STATUS = "Cancelled"
ERROR_STATUS = "Error"

REPORT_STATUS_CHOICE = (
    (IN_PROGRESS_STATUS, IN_PROGRESS_STATUS),
    (READY_STATUS, READY_STATUS),
    (CANCELLED_STATUS, CANCELLED_STATUS),
    (ERROR_STATUS, ERROR_STATUS),
)

MAX_REPORT_RETRY_DEFAULT = 5

AC_SPAPI_REPORT_RETRY_CODE = "FATAL"
