# Generated by Django 5.1.4 on 2025-01-06 08:09

import django.core.validators
import django.utils.timezone
import django_better_admin_arrayfield.models.fields
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalOrganizationalPayment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_internal_users', models.IntegerField(blank=True, null=True)),
                ('max_external_users', models.IntegerField(blank=True, null=True)),
                ('max_workspaces', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovalOrganizationalServiceConfig',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CouponCodeHistory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='FundPackage',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_fund_package_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('balance', models.BigIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapWatcherConfig',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('STANDARD', 'Standard'), ('INDIVIDUAL', 'Individual'), ('PROFESSIONAL', 'Professional'), ('BUSINESS', 'Business'), ('ENTERPRISE', 'Enterprise'), ('DEMAND', 'Demand'), ('CUSTOM', 'Custom')], max_length=100, unique=True)),
                ('plan_config', models.JSONField(default=dict)),
                ('daily_limitation', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapWatcherConfigOnDemand',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenancy_on_demand', models.JSONField()),
                ('plan_config_on_demand', models.JSONField()),
                ('daily_limitation', models.JSONField()),
                ('is_created_on_stripe', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=256)),
                ('trial_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('application', models.CharField(choices=[('transit', '2D Transit'), ('mwrw', 'MAP Watcher'), ('data_central', 'Data Central')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_plan_id', models.CharField(blank=True, max_length=256, null=True)),
                ('application', models.CharField(choices=[('transit', '2D Transit'), ('mwrw', 'MAP Watcher'), ('data_central', 'Data Central')], max_length=100)),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('STANDARD', 'Standard'), ('INDIVIDUAL', 'Individual'), ('PROFESSIONAL', 'Professional'), ('BUSINESS', 'Business'), ('ENTERPRISE', 'Enterprise'), ('DEMAND', 'Demand'), ('CUSTOM', 'Custom')], max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('criteria', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('period', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('3-month', 'Every 3 months'), ('6-month', 'Every 6 months'), ('yearly', 'Yearly')], max_length=100, null=True)),
                ('trial_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.IntegerField(default=1)),
                ('max_internal_users', models.IntegerField(blank=True, default=-1, null=True)),
                ('max_external_users', models.IntegerField(blank=True, default=-1, null=True)),
                ('max_workspaces', models.IntegerField(blank=True, default=-1, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_stripe_id', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application', models.CharField(choices=[('transit', '2D Transit'), ('mwrw', 'MAP Watcher'), ('data_central', 'Data Central')], max_length=100, null=True)),
                ('external_subscription_id', models.CharField(max_length=100, null=True)),
                ('expired_in', models.DateTimeField(default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('POST_PAID', 'Post paid'), ('PRE_PAID', 'Pre paid'), ('FULL_PACK', 'Fully package')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionActivity',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('GRADE_CHANGE', 'Grade change'), ('PREVIEW_NEW_PLAN', 'Preview new plan'), ('UNSUBSCRIBE', 'Unsubscribe'), ('CHANGE_DEFAULT_PAYMENT', 'Change default payment'), ('DELETE_PAYMENT_METHOD', 'Delete payment method')], max_length=100)),
                ('data', models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCouponCode',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_coupon_id', models.IntegerField(editable=False)),
                ('duration_mode', models.CharField(choices=[('once', 'Once'), ('forever', 'Forever'), ('repeating', 'Repeating')], max_length=100)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('discount_id', models.CharField(max_length=100)),
                ('coupon_promotion_code', models.CharField(max_length=100)),
                ('amount_off', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('percent_off', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('is_valid', models.BooleanField()),
                ('is_active', models.BooleanField(default=False)),
                ('raw', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=100)),
                ('external_subscription_id', models.CharField(max_length=100, null=True)),
                ('raw_data', models.JSONField(blank=True, default=None, null=True)),
                ('object_type', models.CharField(max_length=100, null=True)),
                ('external_created_time', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
