# Generated by Django 5.1.4 on 2025-01-06 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('tenancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalorganizationalpayment',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenancies.organization'),
        ),
        migrations.AddField(
            model_name='approvalorganizationalserviceconfig',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenancies.organization'),
        ),
        migrations.AddIndex(
            model_name='couponcodehistory',
            index=models.Index(fields=['discount_id'], name='payments_co_discoun_b809e0_idx'),
        ),
        migrations.AddField(
            model_name='mapwatcherconfigondemand',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancies.organization'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['external_plan_id'], name='payments_pl_externa_2c0817_idx'),
        ),
        migrations.AddField(
            model_name='mapwatcherconfigondemand',
            name='plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.plan'),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenancies.organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.plan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalorganizationalpayment',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionactivity',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptioncouponcode',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptioncouponcode',
            name='user_redeemed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_subscription_id', 'transaction_type'], name='payments_tr_externa_3e3c07_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['external_subscription_id'], name='payments_su_externa_4c3209_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncouponcode',
            index=models.Index(fields=['subscription', 'is_active'], name='payments_su_subscri_d7ae31_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncouponcode',
            index=models.Index(fields=['subscription', 'coupon_promotion_code'], name='payments_su_subscri_8364f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptioncouponcode',
            unique_together={('subscription', 'coupon_promotion_code', 'internal_coupon_id')},
        ),
    ]
