# Generated by Django 3.1.14 on 2023-02-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0001_initial'),
        ('es', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esclientconfig',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal'),
        ),
        migrations.AddField(
            model_name='esclientconfig',
            name='es',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='es.esconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='esclientconfig',
            unique_together={('client', 'es')},
        ),
    ]
