# Status
EDI_INVOICE_PENDING = 'Pending'
EDI_INVOICE_PROCESS = 'Process'
EDI_INVOICE_DONE = 'Done'
EDI_INVOICE_ERROR = 'Error'

EDI_INVOICE_CHOICE = (
    (EDI_INVOICE_PENDING, EDI_INVOICE_PENDING),
    (EDI_INVOICE_PROCESS, EDI_INVOICE_PROCESS),
    (EDI_INVOICE_DONE, EDI_INVOICE_DONE),
    (EDI_INVOICE_ERROR, EDI_INVOICE_ERROR)
)