# Generated by Django 3.1.14 on 2023-05-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whilelist',
            name='ip_addr',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
