from app.financial.variable.data_flatten_variable import FLATTEN_SALE_ITEM_KEY, FLATTEN_SALE_ITEM_FINANCIAL_KEY, \
    FLATTEN_TOP_STYLES_DAILY_KEY, FLATTEN_TOP_STYLES_MTD_KEY, FLATTEN_TOP_STYLES_YTD_KEY, \
    FLATTEN_TOP_STYLES_30_DAYS_KEY, FLATTEN_YOY_MONTHLY_SALE_KEY, FLATTEN_YOY_30_DAY_SALE_KEY, \
    FLATTEN_SALE_BY_DOLLAR_KEY, FLATTEN_SALE_BY_UNIT_KEY, FLATTEN_ADVERTISING_KEY, FLATTEN_SALE_BIG_MOVES_KEY, \
    FLATTEN_ALL_SALE_COMPARISON_KEY, FLATTEN_PRODUCT_COMPARISON_KEY, FLATTEN_PRODUCT_TYPE_COMPARISON_KEY, \
    FLATTEN_PARENT_ASIN_COMPARISON_KEY, FLATTEN_PRODUCT_SALE_KEY, FLATTEN_FF_MONTHLY_SALE_KEY, \
    FLATTEN_BRAND_30_DAY_SALE_KEY, FLATTEN_SALE_BY_DIVISION_KEY, FLATTEN_OVERALL_SALES_KEY, FLATTEN_BROKEN_DOWN_SALE_KEY

SALE_ITEM_INDEX_TEMPLATE = "flatten_sale_items_{client_id}"
SALE_FINANCIAL_INDEX_TEMPLATE = "flatten_sale_financial_{client_id}"
YOY_MONTHLY_INDEX_TEMPLATE = "flatten_yoy_monthly_sale_{client_id}"
YOY_30_DAY_SALE_INDEX_TEMPLATE = "flatten_yoy_30_day_sale_{client_id}"
SALE_BY_DOLLAR_INDEX_TEMPLATE = "flatten_sale_by_dollar_{client_id}"
SALE_BY_UNIT_INDEX_TEMPLATE = "flatten_sale_by_unit_{client_id}"
ADVERTISING_INDEX_TEMPLATE = "flatten_advertising_{client_id}"
SALE_BIG_MOVES_INDEX_TEMPLATE = "flatten_sale_big_moves_{client_id}"
ALL_SALE_COMPARISION_INDEX_TEMPLATE = "flatten_sale_comparision_{client_id}"
PRODUCT_COMPARISON_INDEX_TEMPLATE = "flatten_prod_comparison_{client_id}"
PRODUCT_TYPE_COMPARISON_INDEX_TEMPLATE = "flatten_prodt_comparison_{client_id}"
PARENT_ASIN_COMPARISON_INDEX_TEMPLATE = "flatten_pasin_comparison_{client_id}"
PRODUCT_SALE_INDEX_TEMPLATE = "flatten_product_sale_{client_id}"
FF_MONTHLY_SALE_INDEX_TEMPLATE = "flatten_ff_monthly_sale_{client_id}"
BRAND_30_DAY_SALE_INDEX_TEMPLATE = "flatten_brand_30_day_sale_{client_id}"
SALE_BY_DIVISION_INDEX_TEMPLATE = "flatten_sale_by_divisions_{client_id}"
OVERALL_SALES_INDEX_TEMPLATE = "flatten_overall_sales_{client_id}"
BROKEN_DOWN_SALE_INDEX_TEMPLATE = "flatten_broken_down_sales_{client_id}"
TSTYLE_DAILY_INDEX_TEMPLATE = "flatten_tstyle_daily_{client_id}"
TSTYLE_MTD_INDEX_TEMPLATE = "flatten_tstyle_mtd_{client_id}"
TSTYLE_YTD_INDEX_TEMPLATE = "flatten_tstyle_ytd_{client_id}"
TSTYLE_30_DAYS_INDEX_TEMPLATE = "flatten_tstyle_30_days_{client_id}"

INDEX_TEMPLATE_CONFIGS = {
    FLATTEN_SALE_ITEM_KEY: SALE_ITEM_INDEX_TEMPLATE,
    FLATTEN_SALE_ITEM_FINANCIAL_KEY: SALE_FINANCIAL_INDEX_TEMPLATE,
    FLATTEN_YOY_MONTHLY_SALE_KEY: YOY_MONTHLY_INDEX_TEMPLATE,
    FLATTEN_YOY_30_DAY_SALE_KEY: YOY_30_DAY_SALE_INDEX_TEMPLATE,
    FLATTEN_SALE_BY_DOLLAR_KEY: SALE_BY_DOLLAR_INDEX_TEMPLATE,
    FLATTEN_SALE_BY_UNIT_KEY: SALE_BY_UNIT_INDEX_TEMPLATE,
    FLATTEN_ADVERTISING_KEY: ADVERTISING_INDEX_TEMPLATE,
    FLATTEN_SALE_BIG_MOVES_KEY: SALE_BIG_MOVES_INDEX_TEMPLATE,
    FLATTEN_ALL_SALE_COMPARISON_KEY: ALL_SALE_COMPARISION_INDEX_TEMPLATE,
    FLATTEN_PRODUCT_COMPARISON_KEY: PRODUCT_COMPARISON_INDEX_TEMPLATE,
    FLATTEN_PRODUCT_TYPE_COMPARISON_KEY: PRODUCT_TYPE_COMPARISON_INDEX_TEMPLATE,
    FLATTEN_PARENT_ASIN_COMPARISON_KEY: PARENT_ASIN_COMPARISON_INDEX_TEMPLATE,
    FLATTEN_PRODUCT_SALE_KEY: PRODUCT_SALE_INDEX_TEMPLATE,
    FLATTEN_FF_MONTHLY_SALE_KEY: FF_MONTHLY_SALE_INDEX_TEMPLATE,
    FLATTEN_BRAND_30_DAY_SALE_KEY: BRAND_30_DAY_SALE_INDEX_TEMPLATE,
    FLATTEN_SALE_BY_DIVISION_KEY: SALE_BY_DIVISION_INDEX_TEMPLATE,
    FLATTEN_OVERALL_SALES_KEY: OVERALL_SALES_INDEX_TEMPLATE,
    FLATTEN_BROKEN_DOWN_SALE_KEY: BROKEN_DOWN_SALE_INDEX_TEMPLATE,
    FLATTEN_TOP_STYLES_DAILY_KEY: TSTYLE_DAILY_INDEX_TEMPLATE,
    FLATTEN_TOP_STYLES_MTD_KEY: TSTYLE_MTD_INDEX_TEMPLATE,
    FLATTEN_TOP_STYLES_YTD_KEY: TSTYLE_YTD_INDEX_TEMPLATE,
    FLATTEN_TOP_STYLES_30_DAYS_KEY: TSTYLE_30_DAYS_INDEX_TEMPLATE
}
