from ..variable.schema_tables.financial import DB_TABLE_SALE_ID, DB_TABLE_SALE_DEFAULT, \
    DB_TABLE_SALE_TEMPLATE, DB_TABLE_SALE_ITEM_ID, DB_TABLE_SALE_ITEM_DEFAULT, DB_TABLE_SALE_ITEM_TEMPLATE, \
    DB_TABLE_ITEM_ID, DB_TABLE_ITEM_DEFAULT, DB_TABLE_ITEM_TEMPLATE, DB_TABLE_SHIPPING_INVOICE_ID, \
    DB_TABLE_SHIPPING_INVOICE_TEMPLATE, DB_TABLE_SHIPPING_INVOICE_DEFAULT

#
DB_TABLE_MANAGED = 'managed'

#
DB_TABLE_RELATION_FIELDS_CONFIGS = {
    DB_TABLE_SALE_ID: {
        DB_TABLE_MANAGED: {
            True: DB_TABLE_SALE_DEFAULT,
            False: DB_TABLE_SALE_TEMPLATE
        }
    },
    DB_TABLE_SALE_ITEM_ID: {
        DB_TABLE_MANAGED: {
            True: DB_TABLE_SALE_ITEM_DEFAULT,
            False: DB_TABLE_SALE_ITEM_TEMPLATE
        }
    },
    DB_TABLE_ITEM_ID: {
        DB_TABLE_MANAGED: {
            True: DB_TABLE_ITEM_DEFAULT,
            False: DB_TABLE_ITEM_TEMPLATE
        }
    },
    DB_TABLE_SHIPPING_INVOICE_ID: {
        DB_TABLE_MANAGED: {
            True: DB_TABLE_SHIPPING_INVOICE_DEFAULT,
            False: DB_TABLE_SHIPPING_INVOICE_TEMPLATE
        }
    },
}

DB_TABLE_RELATION_FIELDS = list(DB_TABLE_RELATION_FIELDS_CONFIGS.keys())
