# Generated by Django 3.1.14 on 2025-06-27 03:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0047_auto_20250627_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='COGSConflict',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('sale_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50),
                 blank=True, default=list, help_text='List of sale IDs (as strings) related to this conflict.', size=None)),
                ('extensiv_cog', models.DecimalField(blank=True, decimal_places=2,
                 max_digits=6, null=True, verbose_name='Extensiv COGs')),
                ('dc_cog', models.DecimalField(blank=True, decimal_places=2,
                 max_digits=6, null=True, verbose_name='Data Central COGs')),
                ('pf_cog', models.DecimalField(blank=True, decimal_places=2,
                 max_digits=6, null=True, verbose_name='PF COGs')),
                ('used_cog', models.CharField(choices=[
                 ('Extensiv', 'Extensiv'), ('Data Central', 'Data Central'), ('PF', 'PF')], max_length=20)),
                ('status', models.CharField(choices=[
                 ('No conflict', 'No conflict'), ('In conflict', 'In conflict')], default='In conflict', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('channel', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='financial.channel')),
                ('client', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal')),
            ],
        ),
        migrations.AddIndex(
            model_name='cogsconflict',
            index=models.Index(
                fields=['sku', 'status'], name='extensiv_co_sku_7613dc_idx'),
        ),
    ]
