# Generated by Django 3.1.14 on 2025-07-07 09:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensiv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cogsconflict',
            name='channel_sale_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(
                max_length=50), blank=True, default=list, help_text='List of sale IDs (as strings) related to this conflict.', size=None),
        ),
    ]
