IMPORT_SALE_DATA_KEY = 'IMPORT_SALE_DATA'
IMPORT_SALE_ITEM_DATA_KEY = 'IMPORT_SALE_ITEM_DATA'
DELETE_SALE_ITEM_DATA_KEY = 'DELETE_SALE_ITEM_DATA'
BULK_DELETE_SALE_ITEM_DATA_KEY = 'BULK_DELETE_SALE_ITEM_DATA'
EDIT_SALE_ITEM_DATA_KEY = 'EDIT_SALE_ITEM_DATA'
BULK_EDIT_SALE_ITEM_DATA_KEY = 'BULK_EDIT_SALE_ITEM_DATA'
REVERT_BULK_EDIT_SALE_ITEM_DATA_KEY = 'REVERT_BULK_EDIT_SALE_ITEM_DATA'
BULK_SYNC_SALE_ITEM_DATA_KEY = 'BULK_SYNC_SALE_ITEM_DATA'
BULK_CUSTOM_REPORT_DATA_KEY = 'BULK_CUSTOM_REPORT_DATA'
REVOKED_ACTION_KEY = 'REVOKED_ACTION'
DELETE_BRAND_DATA_KEY = 'DELETE_BRAND_DATA'
REVOKED_SP_REPORT_KEY = 'REVOKED_SP_REPORT'
CONNECTION_SP_ACCOUNT_KEY = 'CONNECTION_SP_ACCOUNT'
REVOKE_SP_ACCOUNT_KEY = 'REVOKE_SP_ACCOUNT'
UPDATE_COGS_SOURCE_SETTINGS_KEY = 'UPDATE_COGS_SOURCE_SETTINGS'

SALE_ITEM_DATA_ACTION_KEYS = [DELETE_SALE_ITEM_DATA_KEY, BULK_DELETE_SALE_ITEM_DATA_KEY, EDIT_SALE_ITEM_DATA_KEY,
                              BULK_EDIT_SALE_ITEM_DATA_KEY, BULK_SYNC_SALE_ITEM_DATA_KEY,
                              REVERT_BULK_EDIT_SALE_ITEM_DATA_KEY, BULK_CUSTOM_REPORT_DATA_KEY]

IMPORT_ITEM_DATA_KEY = 'IMPORT_ITEM_DATA'
CREATE_ITEM_DATA_KEY = 'CREATE_ITEM_DATA'
UPDATE_ITEM_DATA_KEY = 'UPDATE_ITEM_DATA'
DELETE_ITEM_DATA_KEY = 'DELETE_ITEM_DATA'
BULK_UPDATE_ITEM_DATA_KEY = 'BULK_UPDATE_ITEM_DATA'
BULK_DELETE_ITEM_DATA_KEY = 'BULK_DELETE_ITEM_DATA'
IMPORT_BRAND_SETTING_DATA_KEY = 'IMPORT_BRAND_SETTING_DATA'

ITEM_DATA_ACTION_KEYS = [IMPORT_ITEM_DATA_KEY, CREATE_ITEM_DATA_KEY, UPDATE_ITEM_DATA_KEY, DELETE_ITEM_DATA_KEY,
                         BULK_UPDATE_ITEM_DATA_KEY, BULK_DELETE_ITEM_DATA_KEY, IMPORT_BRAND_SETTING_DATA_KEY]

SYNC_CLIENT_PORTAL_KEY = 'SYNC_CLIENT_PORTAL'

IMPORT_FEDEX_SHIPMENT_DATA_KEY = 'IMPORT_FEDEX_SHIPMENT_DATA'
IMPORT_APP_EAGLE_PROFILE_DATA_KEY = 'IMPORT_APP_EAGLE_PROFILE_DATA'

IMPORT_TOP_ASINS_DATA_KEY = 'IMPORT_TOP_ASINS_DATA'
IMPORT_DELETE_TOP_ASINS_DATA_KEY = 'IMPORT_DELETE_TOP_ASINS_DATA'
CREATE_TOP_ASINS_DATA_KEY = 'CREATE_TOP_ASINS_DATA'
UPDATE_TOP_ASINS_DATA_KEY = 'UPDATE_TOP_ASINS_DATA'
DELETE_TOP_ASINS_DATA_KEY = 'DELETE_TOP_ASINS_DATA'

# Action of Activity
ACTION_ACTIVITY = (
    (IMPORT_SALE_DATA_KEY, 'Import Sale Data'),
    (IMPORT_SALE_ITEM_DATA_KEY, 'Import Sale Item Data'),
    (DELETE_SALE_ITEM_DATA_KEY, 'Delete Sale Item Data'),
    (BULK_DELETE_SALE_ITEM_DATA_KEY, 'Bulk Delete Sale Item Data'),
    (EDIT_SALE_ITEM_DATA_KEY, 'Edit Sale Item Data'),
    (BULK_EDIT_SALE_ITEM_DATA_KEY, 'Bulk Edit Sale Item Data'),
    (BULK_SYNC_SALE_ITEM_DATA_KEY, 'Bulk Sync Sale Item Data'),
    (IMPORT_ITEM_DATA_KEY, 'Import Item Data'),
    (CREATE_ITEM_DATA_KEY, 'Create Item Data'),
    (UPDATE_ITEM_DATA_KEY, 'Update Item Data'),
    (BULK_UPDATE_ITEM_DATA_KEY, 'Bulk Update Item Data'),
    (BULK_DELETE_ITEM_DATA_KEY, 'Bulk Delete Item Data'),
    (SYNC_CLIENT_PORTAL_KEY, 'Sync Client Portal'),
    (IMPORT_BRAND_SETTING_DATA_KEY, 'Import Brand Setting Data'),
    (IMPORT_FEDEX_SHIPMENT_DATA_KEY, 'Import FedEx Shipment Data'),
    (IMPORT_APP_EAGLE_PROFILE_DATA_KEY, 'Import App Eagle Profile Data'),
    (REVERT_BULK_EDIT_SALE_ITEM_DATA_KEY, 'Revert Bulk Edit Sale Item Data'),
    (BULK_CUSTOM_REPORT_DATA_KEY, 'Bulk Custom Report Data'),
    (REVOKED_ACTION_KEY, 'Revoked Action'),
    (CONNECTION_SP_ACCOUNT_KEY, 'Connection Selling Partner Account'),
    (REVOKE_SP_ACCOUNT_KEY, 'Revoked Selling Partner Account'),
    (UPDATE_COGS_SOURCE_SETTINGS_KEY, 'Update COGS Source Settings'),
)
