# Shipping Cost
EVALUATED_SHIPPING_COST_ACCURACY_ACCEPT_CALCULATE = 99
#
EVALUATED_SHIPPING_COST_ACCURACY_SPECIFIC_BRAND_MFN_PRIME = 70
EVALUATED_SHIPPING_COST_ACCURACY_SPECIFIC_BRAND_MFN_DS = 90
EVALUATED_SHIPPING_COST_ACCURACY_SPECIFIC_BRAND = 80
EVALUATED_SHIPPING_COST_ACCURACY_DEFAULT_BRAND = 50

# Warehouse Processing Fee
EVALUATED_DROP_SHIP_FEE_ACCURACY_ACCEPT_CALCULATE = 99

# Freight Cost
EVALUATED_FREIGHT_COST_ACCURACY_SPECIFIC_BRAND = 50

#
MFN_DROP_SHIP = "Dropship"
MFN_RAPID_ACCESS = "Rapid Access"
MFN_STANDARD = "Standard"
VALID_MFN_FORMULA = [None, MFN_DROP_SHIP, MFN_RAPID_ACCESS, MFN_STANDARD, ""]

#
PO_DROPSHIP_COST_METHOD = 'Cost'
PO_DROPSHIP_PERCENT_METHOD = 'Percent'
PO_DROPSHIP_METHOD_CHOICES = (
    (PO_DROPSHIP_COST_METHOD, PO_DROPSHIP_COST_METHOD),
    (PO_DROPSHIP_PERCENT_METHOD, PO_DROPSHIP_PERCENT_METHOD)
)

PO_DROPSHIP_METHOD_LIST = [item[0] for item in PO_DROPSHIP_METHOD_CHOICES]
