DATA_CENTRAL = 'data_central'
AMAZON_SELLER_CENTRAL = 'amazon_seller_central'

BULK_SYNC_DATASOURCE_CHOICE = (
    (AMAZON_SELLER_CENTRAL, 'Amazon Seller Central'),
    (DATA_CENTRAL, 'Data Central'),
)
BULK_SYNC_DATASOURCE_LIST = list(item[0] for item in BULK_SYNC_DATASOURCE_CHOICE)

OPEN_STATUS = 'Open'
ERROR_STATUS = 'Error'
DONE_STATUS = 'Done'
REVOKED_STATUS = 'Revoked'

BULK_SYNC_CHUNK_STATUS = (
    (OPEN_STATUS, OPEN_STATUS),
    (ERROR_STATUS, ERROR_STATUS),
    (DONE_STATUS, DONE_STATUS),
    (REVOKED_STATUS, REVOKED_STATUS)
)