SPAPI_RECONNECT_DEFAULT_TYPE = "default"
SPAPI_RECONNECT_ROTATION_DATELINE_TYPE = "rotation_date_line"
SPAPI_RECONNECT_LWA_SECRET_KEY_TYPE = "lwa_secret_key"

SPAPI_RECONNECT_TYPE = (
    (SPAPI_RECONNECT_DEFAULT_TYPE, "Default"),
    (SPAPI_RECONNECT_ROTATION_DATELINE_TYPE, "Rotation Dateline"),
    (SPAPI_RECONNECT_LWA_SECRET_KEY_TYPE, "LWA Secret Key")
)
