# Sources
FLATTEN_PG_SOURCE = "PG"
FLATTEN_ES_SOURCE = "ES"

FLATTEN_SOURCES = (
    (FLATTEN_PG_SOURCE, "Postgres"),
    (FLATTEN_ES_SOURCE, "Elasticsearch")
)

FLATTEN_SOURCES_LIST = [item[0] for item in FLATTEN_SOURCES]

# Key DS Orders
FLATTEN_SALE_ITEM_KEY = "SALE_ITEMS"
FLATTEN_SALE_ITEM_FINANCIAL_KEY = "SALE_FINANCIAL"

# Key DS Calculate
FLATTEN_YOY_MONTHLY_SALE_KEY = "YOY_MONTHLY_SALE"
FLATTEN_YOY_30_DAY_SALE_KEY = "YOY_30_DAY_SALE"
FLATTEN_SALE_BY_DOLLAR_KEY = "SALE_BY_DOLLAR"
FLATTEN_SALE_BY_UNIT_KEY = "SALE_BY_UNIT"
FLATTEN_ADVERTISING_KEY = "ADVERTISING"
FLATTEN_SALE_BIG_MOVES_KEY = "SALE_BIG_MOVES"
FLATTEN_BRAND_30_DAY_SALE_KEY = "BRAND_30_DAY_SALE"
FLATTEN_ALL_SALE_COMPARISON_KEY = "SALE_COMPARISION"
FLATTEN_PRODUCT_COMPARISON_KEY = "PROD_COMPARISON"
FLATTEN_PRODUCT_TYPE_COMPARISON_KEY = "PRODT_COMPARISON"
FLATTEN_PARENT_ASIN_COMPARISON_KEY = "PASIN_COMPARISON"
FLATTEN_PRODUCT_SALE_KEY = "PRODUCT_SALE"
FLATTEN_FF_MONTHLY_SALE_KEY = "FF_MONTHLY_SALE"  # Fulfillment Monthly Sales
FLATTEN_SALE_BY_DIVISION_KEY = "SALE_BY_DIVISIONS"
FLATTEN_OVERALL_SALES_KEY = "OVERALL_SALES"
FLATTEN_BROKEN_DOWN_SALE_KEY = "BROKEN_DOWN_SALES"
FLATTEN_TOP_STYLES_DAILY_KEY = "TSTYLE_DAILY"
FLATTEN_TOP_STYLES_MTD_KEY = "TSTYLE_MTD"
FLATTEN_TOP_STYLES_YTD_KEY = "TSTYLE_YTD"
FLATTEN_TOP_STYLES_30_DAYS_KEY = "TSTYLE_30_DAYS"

DATA_FLATTEN_TYPE = (
    (FLATTEN_SALE_ITEM_KEY, "View Sale Items"),
    (FLATTEN_SALE_ITEM_FINANCIAL_KEY, "Sale Financial Item"),
    (FLATTEN_YOY_MONTHLY_SALE_KEY, "YOY Monthly Sales"),
    (FLATTEN_YOY_30_DAY_SALE_KEY, "YOY 30 Day Sales"),
    (FLATTEN_SALE_BY_DOLLAR_KEY, "Sale By Dollar"),
    (FLATTEN_SALE_BY_UNIT_KEY, "Sale By Unit"),
    (FLATTEN_ADVERTISING_KEY, "Advertising"),
    (FLATTEN_SALE_BIG_MOVES_KEY, "Sale Big Moves"),
    (FLATTEN_ALL_SALE_COMPARISON_KEY, "All Sale Comparison"),
    (FLATTEN_PRODUCT_COMPARISON_KEY, "All Sale Product Comparison"),
    (FLATTEN_PRODUCT_TYPE_COMPARISON_KEY, "All Sale Product Type Comparison"),
    (FLATTEN_PARENT_ASIN_COMPARISON_KEY, "All Sale Parent ASIN Comparison"),
    (FLATTEN_PRODUCT_SALE_KEY, "Ordered Product Sales"),
    (FLATTEN_FF_MONTHLY_SALE_KEY, "Fulfillment Monthly Sales"),
    (FLATTEN_BRAND_30_DAY_SALE_KEY, "Brand 30 Day Sales"),
    (FLATTEN_SALE_BY_DIVISION_KEY, "Sale By Divisions"),
    (FLATTEN_OVERALL_SALES_KEY, "Overall Sales"),
    (FLATTEN_BROKEN_DOWN_SALE_KEY, "Broken Down Sales"),
    (FLATTEN_TOP_STYLES_DAILY_KEY, "Top Performing Styles Daily"),
    (FLATTEN_TOP_STYLES_MTD_KEY, "Top Performing Styles MTD"),
    (FLATTEN_TOP_STYLES_YTD_KEY, "Top Performing Styles YTD"),
    (FLATTEN_TOP_STYLES_30_DAYS_KEY, "Top Performing Styles 30 Days"),
)

DATA_FLATTEN_TYPE_LIST = [item[0] for item in DATA_FLATTEN_TYPE]

DATA_FLATTEN_TYPE_ANALYSIS_LIST = [FLATTEN_SALE_ITEM_KEY, FLATTEN_SALE_ITEM_FINANCIAL_KEY]

DATA_FLATTEN_DASHBOARD_OVERVIEW_TYPE = "dashboard_overview"
DATA_FLATTEN_DASHBOARD_ADVERTISING_TYPE = "dashboard_advertising"

DATA_FLATTEN_DASHBOARD_TYPE = {
    DATA_FLATTEN_DASHBOARD_OVERVIEW_TYPE: [
        FLATTEN_YOY_MONTHLY_SALE_KEY,
        FLATTEN_YOY_30_DAY_SALE_KEY,
        FLATTEN_SALE_BY_DOLLAR_KEY,
        FLATTEN_SALE_BIG_MOVES_KEY,
        FLATTEN_BRAND_30_DAY_SALE_KEY,
        FLATTEN_ALL_SALE_COMPARISON_KEY,
        FLATTEN_PRODUCT_COMPARISON_KEY,
        FLATTEN_PRODUCT_TYPE_COMPARISON_KEY,
        FLATTEN_PARENT_ASIN_COMPARISON_KEY,
        FLATTEN_SALE_BY_UNIT_KEY,
        FLATTEN_PRODUCT_SALE_KEY,
        FLATTEN_FF_MONTHLY_SALE_KEY,
        FLATTEN_SALE_BY_DIVISION_KEY,
        FLATTEN_OVERALL_SALES_KEY,
        FLATTEN_BROKEN_DOWN_SALE_KEY,
        FLATTEN_TOP_STYLES_DAILY_KEY,
        FLATTEN_TOP_STYLES_MTD_KEY,
        FLATTEN_TOP_STYLES_YTD_KEY,
        FLATTEN_TOP_STYLES_30_DAYS_KEY
    ],
    DATA_FLATTEN_DASHBOARD_ADVERTISING_TYPE: [FLATTEN_ADVERTISING_KEY]
}

DATA_FLATTEN_TYPE_CALCULATE_LIST = DATA_FLATTEN_DASHBOARD_TYPE[DATA_FLATTEN_DASHBOARD_OVERVIEW_TYPE]

DATA_FLATTEN_ANALYSIS_INDEXES_CONFIG = [
    {"columns": ["channel_name", "sale_date"], "type": "BRIN"},
    {"columns": ["channel_name", "item_sale_status"]},
    {"columns": ["channel_name", "brand"]},
    {"columns": ["channel_name", "channel_id"]},
    {"columns": ["channel_name", "fulfillment_type"]},
    {"columns": ["channel_name", "sale_date", "brand"], "type": "BRIN"},
    {"columns": ["channel_name", "item_sale_status", "brand"]},
    {"columns": ["channel_name", "sale_date", "brand", "fulfillment_type"], "type": "BRIN"},
    {"columns": ["channel_name", "item_sale_status", "brand", "fulfillment_type"]}
]

# Source default ES
FLATTEN_SOURCES_ES_DEFAULT = [FLATTEN_SALE_ITEM_KEY, FLATTEN_SALE_ITEM_FINANCIAL_KEY]

CREATE_SOURCE_BY_QUERY = "CREATE_SOURCE_BY_QUERY"
CREATE_SOURCE_BY_SCHEMA = "CREATE_SOURCE_BY_SCHEMA"
UPDATE_SOURCE_BY_BUILD_UPSERT_QUERY = "UPDATE_SOURCE_BY_BUILD_UPSERT_QUERY"
UPDATE_SOURCE_BY_BUILD_INSERT_QUERY = "UPDATE_SOURCE_BY_BUILD_INSERT_QUERY"
UPDATE_SOURCE_BY_SEGMENT_INSERT_QUERY = "UPDATE_SOURCE_BY_SEGMENT_INSERT_QUERY"
