from app.financial.variable.data_flatten_variable import FLATTEN_YOY_30_DAY_SALE_KEY, FLATTEN_SALE_ITEM_KEY

DATA_FEED_FILE_SIZE = 10000

DATA_FEED_TYPE_CHOICES = (
    (FLATTEN_SALE_ITEM_KEY, "Sale Item Feed"),
    (FLATTEN_YOY_30_DAY_SALE_KEY, "YOY 30 Day Sales Feed")
)

DATA_FEED_TYPE_LIST = [item[0] for item in DATA_FEED_TYPE_CHOICES]

FEED_ACTION_SCHEDULER = 'FEED_RUN_SCHEDULER'
FEED_ACTION_ON_DEMAND = 'FEED_RUN_ON_DEMAND'

FEED_RUN_TYPES_CHOICES = (
    (FEED_ACTION_SCHEDULER, 'Feed Action Scheduler'),
    (FEED_ACTION_ON_DEMAND, 'Feed Action OnDemand'),
)
