FULFILLMENT_FBA = 'FBA'
FULFILLMENT_MFN = 'MFN'
FULFILLMENT_MFN_RA = 'MFN-RA'
FULFILLMENT_MFN_PRIME = 'MFN-Prime'
FULFILLMENT_MFN_DS = 'MFN-DS'
FULFILLMENT_MFN_GROUP = [FULFILLMENT_MFN, FULFILLMENT_MFN_RA, FULFILLMENT_MFN_PRIME, FULFILLMENT_MFN_DS]

#
FULFILLMENT_MFN_PRIME_ACCURACY_DEFAULT = 100
