PROJECTED_STATUS = 'Projected'
AUDITED_STATUS = 'Audited'
FINAL_STATUS = 'Final'

PROFIT_STATUS = (
    ((PROJECTED_STATUS, PROJECTED_STATUS), 1000),
    ((AUDITED_STATUS, AUDITED_STATUS), 2000),
    ((FINAL_STATUS, FINAL_STATUS), 3000),
)

PROFIT_STATUS_ENUM = tuple(item[0] for item in PROFIT_STATUS)

PROFIT_STATUS_ORDER_DICT = {item[0][0]: item[1] for item in PROFIT_STATUS}
