from app.financial.variable.brand_setting import EVALUATED_SHIPPING_COST_ACCURACY_SPECIFIC_BRAND_MFN_DS, \
    EVALUATED_SHIPPING_COST_ACCURACY_SPECIFIC_BRAND, EVALUATED_SHIPPING_COST_ACCURACY_SPECIFIC_BRAND_MFN_PRIME
from app.financial.variable.fulfillment_type import FULFILLMENT_MFN_DS, FULFILLMENT_FBA, FULFILLMENT_MFN, \
    FULFILLMENT_MFN_PRIME, FULFILLMENT_MFN_RA

BRAND_SETTING_SOURCE_KEY = 'BrandSetting'
FEDEX_SHIPMENT_SOURCE_KEY = 'FedEx'
AMZ_POSTAGE_BILLING_SOURCE_KEY = 'AMZPostageBilling'
AMZ_FBA_FULFILLMENT_FEE_SOURCE_KEY = 'AMZFBAFulfillmentFee'
AMZ_SELLER_CENTRAL_SOURCE_KEY = 'AMZSellerCentral'
SINGLE_EDIT_SOURCE_KEY = "SingleEdit"
BULK_EDIT_SOURCE_KEY = "BulkEdit"
IMPORT_SOURCE_KEY = "Import"

SHIPPING_COST_ACCURACY_BY_SOURCE = {
    BRAND_SETTING_SOURCE_KEY: {
        FULFILLMENT_MFN_PRIME: EVALUATED_SHIPPING_COST_ACCURACY_SPECIFIC_BRAND_MFN_PRIME,
        FULFILLMENT_FBA: EVALUATED_SHIPPING_COST_ACCURACY_SPECIFIC_BRAND,
        FULFILLMENT_MFN_DS: EVALUATED_SHIPPING_COST_ACCURACY_SPECIFIC_BRAND_MFN_DS,
        FULFILLMENT_MFN_RA: EVALUATED_SHIPPING_COST_ACCURACY_SPECIFIC_BRAND,
        FULFILLMENT_MFN: EVALUATED_SHIPPING_COST_ACCURACY_SPECIFIC_BRAND
    },  # It's depend on fulfillment type of Orders
    FEDEX_SHIPMENT_SOURCE_KEY: 100,
    AMZ_POSTAGE_BILLING_SOURCE_KEY: 75,
    AMZ_FBA_FULFILLMENT_FEE_SOURCE_KEY: 100,
    AMZ_SELLER_CENTRAL_SOURCE_KEY: 75
}

SHIPPING_COST_SOURCE_TRANS_EVENT = [AMZ_FBA_FULFILLMENT_FEE_SOURCE_KEY, AMZ_POSTAGE_BILLING_SOURCE_KEY]

SHIPPING_COST_SOURCE = (
    (BRAND_SETTING_SOURCE_KEY, BRAND_SETTING_SOURCE_KEY),
    (FEDEX_SHIPMENT_SOURCE_KEY, FEDEX_SHIPMENT_SOURCE_KEY),
    (AMZ_POSTAGE_BILLING_SOURCE_KEY, AMZ_POSTAGE_BILLING_SOURCE_KEY),
    (AMZ_FBA_FULFILLMENT_FEE_SOURCE_KEY, AMZ_FBA_FULFILLMENT_FEE_SOURCE_KEY)
)

SHIP_CARRIER_UPS = 'UPS'
SHIP_CARRIER_USPS = 'USPS'
SHIP_CARRIER_FEDEX = 'FedEx'

SHIP_CARRIER_LIST_TYPE = [SHIP_CARRIER_UPS, SHIP_CARRIER_USPS, SHIP_CARRIER_FEDEX]
