SIMILAR_STATUS = 'SIMILAR'
DIFFERENT_STATUS = 'DIFFERENT'

SKU_VAULT_PRIME_TRACK_CONFIG = (
    (SIMILAR_STATUS, SIMILAR_STATUS),
    (DIFFERENT_STATUS, DIFFERENT_STATUS)
)

SKUVAULT_SOURCE = 'SKUVaultSource'
CART_ROVER_SOURCE = 'CartRoverSource'
THIRD_PARTY_LOGISTIC_SOURCE = '3PLCentral'

PRIME_TRACK_SOURCE_CONFIG = (
    (SKUVAULT_SOURCE, 'SKU Vault'),
    (CART_ROVER_SOURCE, 'Cart Rover'),
    (THIRD_PARTY_LOGISTIC_SOURCE, '3PL Central')
)
