SALE_ID_START_NUMBER = 3000000

VARIANT_SIZE_TYPE = 'Size'
VARIANT_STYLE_TYPE = 'Style'

VARIANT_TYPE = (
    (VARIANT_SIZE_TYPE, 'Size'),
    (VARIANT_STYLE_TYPE, 'Style')
)

VIEW_PERMISSION = 'view'
EDIT_PERMISSION = 'edit'

SHARE_PERMISSION_TYPE = (
    (VIEW_PERMISSION, 'View'),
    (EDIT_PERMISSION, 'Edit')
)

PRIVATE_MODE = 0
PUBLIC_MODE = 1

SHARE_MODE_TYPE = (
    (PRIVATE_MODE, 'private'),
    (PUBLIC_MODE, 'public')
)
