"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import datetime
import os

import environ
from Crypto.PublicKey import RSA

from app import __version__

#
env = environ.Env()
env.read_env()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT_DIR = environ.Path(__file__) - 3

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

#  Environment
ENVIRONMENT = env("ENVIRONMENT")

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

BASE_URL = env.str("BASE_URL", default="http://localhost:8000")

ALLOWED_HOSTS = []

# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "rest_framework.authtoken",
    "oauth2_provider",
    "dj_rest_auth",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "dj_rest_auth.registration",
    "stripe",
    "drf_yasg",
    "corsheaders",
    "django_celery_beat",
    "django_celery_results",
    "auditlog",
    "django_better_admin_arrayfield",
    "adminsortable",
    "django_json_widget",
    "django_pgviews",
    "admin_auto_filters",
    "silk",
    "durationwidget",
]

# Apps specific for this project go here.
LOCAL_APPS = [
    "app.core.apps.CoreConfig",
    "app.tenancies.apps.TenanciesConfig",
    "app.permission.apps.PermissionConfig",
    "app.social_auth.apps.SocialAuthConfig",
    "app.payments.apps.PaymentConfig",
    "app.app_setting.apps.AppSettingConfig"
]

SITE_ID = 1

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

BUGSNAG = {
    "api_key": env("BUGSNAG_API_KEY"),
    "params_filters": [
        "password",
        "password_confirmation",
        "authorization",
        "aws_",
        "database",
        "redis",
    ],
    "release_stage": ENVIRONMENT,
    "notify_release_stages": ["production", "development", "uat", "qa"],
    "app_version": __version__,
}

MIDDLEWARE = [
    "bugsnag.django.middleware.BugsnagMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "oauth2_provider.middleware.OAuth2TokenMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
    # "app.core.context.PortalAppContextMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ENABLED_DJANGO_SILK = env.bool("ENABLED_DJANGO_SILK", default=False)
if ENABLED_DJANGO_SILK:
    MIDDLEWARE.append("silk.middleware.SilkyMiddleware")
    # SILKY_AUTHENTICATION = True  # User must login
    # SILKY_AUTHORISATION = True
    SILKY_INTERCEPT_PERCENT = 50

AUTHENTICATION_BACKENDS = (
    # Uncomment following if you want to access the admin
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

# Auth model
AUTH_USER_MODEL = "tenancies.User"

# Route
ROOT_URLCONF = "config.urls"

# Templates
TEMPLATES_ROOT = str(ROOT_DIR("templates"))
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATES_ROOT],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL", default="postgres:///goldfish"),
}
DATABASES["default"]["ATOMIC_REQUESTS"] = True
# DB_NAME_RUNNING_TEST = env("DB_NAME_RUNNING_TEST", default="portal_unit_test")
# DATABASES["default"]["TEST"] = {"NAME": DB_NAME_RUNNING_TEST}
# Update these test database settings
DATABASES["default"]["TEST"] = {
    "NAME": env("DB_NAME_RUNNING_TEST", default="portal_unit_test"),  # Name for the test database
    "CREATE_DB": True,  # Ensure Django creates the test database
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

# STATIC FILE CONFIGURATION
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = str(ROOT_DIR("staticfiles"))

# See: https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = "/static/"

REST_FRAMEWORK = {
    "COERCE_DECIMAL_TO_STRING": False,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        "app.core.simple_authentication.JWTTokenHandlerAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    #  'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',  # LimitOffsetPagination
    "DEFAULT_PAGINATION_CLASS": "app.core.pagination.StandardResultsSetPagination",  # LimitOffsetPagination
    "PAGE_SIZE": env.int("PAGE_SIZE", 20),
    "PAGINATE_BY_PARAM": "page_size",  # Allow client to override, using `?page_size=xxx`.
    "MAX_PAGINATE_BY": 500,  # Maximum limit allowed when using `?page_size=xxx`.
    # 'DATE_INPUT_FORMATS': ['YYYY-MM-DD HH:MM:SS'],
    "EXCEPTION_HANDLER": "app.core.exception_handler.api_exception_handler",
}

#  Rest Auth
# TODO: PS-906
# REST_AUTH_SERIALIZERS = {
#     "PASSWORD_RESET_SERIALIZER": "app.tenancies.serializers.PasswordResetSerializer",
#     "PASSWORD_RESET_CONFIRM_SERIALIZER": "app.tenancies.serializers.PasswordResetConfirmSerializer",
#     "USER_DETAILS_SERIALIZER": "app.tenancies.serializers.UserDetailsSerializer",
#     "LOGIN_SERIALIZER": "app.tenancies.serializers.CustomLoginSerializer",
# }

# REST_AUTH_REGISTER_SERIALIZERS = {
#     "REGISTER_SERIALIZER": "app.tenancies.serializers.CustomRegisterSerializer",
# }

REST_AUTH = {
    'OLD_PASSWORD_FIELD_ENABLED': True,
    "PASSWORD_RESET_SERIALIZER": "app.tenancies.serializers.PasswordResetSerializer",
    "PASSWORD_RESET_CONFIRM_SERIALIZER": "app.tenancies.serializers.PasswordResetConfirmSerializer",
    "USER_DETAILS_SERIALIZER": "app.tenancies.serializers.UserDetailsSerializer",
    "LOGIN_SERIALIZER": "app.tenancies.serializers.CustomLoginSerializer",
    "REGISTER_SERIALIZER": "app.tenancies.serializers.CustomRegisterSerializer",
}

# TODO: PS-906
# OLD_PASSWORD_FIELD_ENABLED = True

ACCOUNT_EMAIL_REQUIRED = True

ACCOUNT_EMAIL_VERIFICATION = "mandatory"

# Allow CORS requests from all domain
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = False

CORS_ALLOW_HEADERS = (
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
)

# domains
DOMAIN_CP = env("DOMAIN_CP", default="localhost")
DOMAIN_OE = env("DOMAIN_OE", default="localhost")
DOMAIN_2D = env("DOMAIN_2D", default="localhost")

#  Celery
IS_CELERY_ENABLED = env.bool(
    "IS_CELERY_ENABLED", default=False
)

BROKER_URL = env("CELERY_BROKER_URL", default="django://")
CELERYD_MAX_TASKS_PER_CHILD = 100
CELERYD_TASK_SOFT_TIME_LIMIT = 2400  # 40 minutes
CELERY_RESULT_BACKEND = "django-db"
CELERY_IGNORE_RESULT = False
CELERY_BEAT_SCHEDULER = (
    "django_celery_beat.schedulers:DatabaseScheduler"  # monitor django admin
)

#  Redis
USER_CLIENT_REDIS_CHANNEL = env(
    "USER_CLIENT_REDIS_CHANNEL", default="redis://redis:6379/0"
)
REDIS_TTL = env.int("REDIS_TTL", 5)
USER_CLIENT_REDIS_ENABLED = env.bool("USER_CLIENT_REDIS_ENABLED", default=False)
PREFIX_REDIS_KEY = env("PREFIX_REDIS_KEY", default="")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": USER_CLIENT_REDIS_CHANNEL,
        "TIMEOUT": int(REDIS_TTL * 60),
        "KEY_PREFIX": PREFIX_REDIS_KEY,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Firebase
USER_CLIENT_FIRE_BASE_ENABLED = env.bool("USER_CLIENT_FIRE_BASE_ENABLED", default=False)
FIRE_BASE_REAL_TIME_DB_URL = env("FIRE_BASE_REAL_TIME_DB_URL")
FIRE_BASE_ACCESS_KEY = env("FIRE_BASE_ACCESS_KEY")
FIRE_BASE_REF = env("FIRE_BASE_REF", default="/")

#  Email Config
EMAIL_BACKEND = env("EMAIL_BACKEND")
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_USE_TLS = env("EMAIL_USE_TLS")
DJANGO_DEFAULT_FROM_EMAIL = env("DJANGO_DEFAULT_FROM_EMAIL")

#  Swagger
SWAGGER_SETTINGS = {
    "USE_SESSION_AUTH": False,
    "SECURITY_DEFINITIONS": {
        "api_key": {"type": "apiKey", "name": "Authorization", "in": "header"}
    },
}

#  JWT`
PRIVATE_KEY_PATH = env("PRIVATE_KEY_PATH")
PUBLIC_KEY_PATH = env("PUBLIC_KEY_PATH")
#  get the current dir of *.pem
f = open(str(ROOT_DIR) + str(PRIVATE_KEY_PATH), "r")
JWT_PRIVATE_KEY = RSA.import_key(f.read())
f.close()
f = open(str(ROOT_DIR) + str(PUBLIC_KEY_PATH), "r")
JWT_PUBLIC_KEY = RSA.import_key(f.read())
f.close()

JWT_EXPIRATION_DELTA = env.int("JWT_EXPIRATION_DELTA", default=5)  # minutes
REST_USE_JWT = True

# JWT_AUTH = {
#     "JWT_PRIVATE_KEY": JWT_PRIVATE_KEY.export_key(),
#     "JWT_PUBLIC_KEY": JWT_PUBLIC_KEY.export_key(),
#     "JWT_ALGORITHM": "RS256",
#     "JWT_ALLOW_REFRESH": True,
#     "JWT_EXPIRATION_DELTA": datetime.timedelta(seconds=60 * int(JWT_EXPIRATION_DELTA)),
#     "JWT_REFRESH_EXPIRATION_DELTA": datetime.timedelta(days=30),
#     "JWT_AUTH_HEADER_PREFIX": "Bearer",
# }

# Simple JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(seconds=60 * int(JWT_EXPIRATION_DELTA)),
    "REFRESH_TOKEN_LIFETIME": datetime.timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "RS256",
    "SIGNING_KEY": JWT_PRIVATE_KEY.export_key(),
    "VERIFYING_KEY": JWT_PUBLIC_KEY.export_key(),
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "email",
    "USER_ID_CLAIM": "email",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": None,
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": None,

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": datetime.timedelta(minutes=60),
    "SLIDING_TOKEN_REFRESH_LIFETIME": datetime.timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

# Services public key path
SERVICE_AUDIENCE = env(
    "SERVICE_AUDIENCE_CONF", default="portal"
)  # this audience is configured for services access
MW_PUBLIC_KEY_PATH = env("MW_PUBLIC_KEY_PATH", default="")
DTD_PUBLIC_KEY_PATH = env("DTD_PUBLIC_KEY_PATH", default="")
# INTERNAL_PUBLIC_KEY_PATH
# for now, using with key pair of PS is acceptable
# could replace by the new one in the future
INTERNAL_PUBLIC_KEY_PATH = env("INTERNAL_PUBLIC_KEY_PATH", default="")
INTERNAL_TOKEN = env.str("INTERNAL_TOKEN", default="")

#  Google Cloud Storage
GOOGLE_CLOUD_STORAGE_BUCKET_NAME = env("GOOGLE_CLOUD_STORAGE_BUCKET_NAME")
GOOGLE_CLOUD_STORAGE_BUCKET_ACCESS_KEY = env("GOOGLE_CLOUD_STORAGE_BUCKET_ACCESS_KEY")

# logging

BASE_LOG_DIR = os.environ.get("BASE_LOG_DIR", default="logs")
LOG_FILE_PATH = os.path.join(BASE_LOG_DIR, "logs.log")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s "
                      "%(process)d %(thread)d %(message)s"
        },
        "simple": {
            "format": "%(levelname)s\t%(asctime)s\t%(filename)s\t%(lineno)d\t%(message)s"
        },
    },
    "root": {
        "level": "INFO",
        "handlers": ["bugsnag", "console", "file"],
    },
    "handlers": {
        # Send info messages to file
        "file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": LOG_FILE_PATH,
            "when": "D",
            "encoding": "utf-8",
            "formatter": "simple",
        },
        # Send messages to console
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        #  critical errors are logged to bugsnag
        "bugsnag": {
            "level": "ERROR",
            "class": "bugsnag.handlers.BugsnagHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

CREDENTIAL_GOOGLE_AUTH_PATH = env("CREDENTIAL_GOOGLE_AUTH_PATH")

# Social logins
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "offline",
        },
    }
}

FERNET_KEY = env.str('FERNET_KEY', default=None)

ACCOUNT_AUTHENTICATION_METHOD = "email"

# Transit app config registration
ONLY_ALLOW_REGISTRATION_FOR_WHITE_LISTED_EMAILS = env(
    "ONLY_ALLOW_REGISTRATION_FOR_WHITE_LISTED_EMAILS", default=False
)

# Stripe payments
STRIPE_PUBLISHABLE_KEY = env("STRIPE_PUBLISHABLE_KEY")
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY")
STRIPE_ENDPOINT_SECRET = env("STRIPE_ENDPOINT_SECRET")

STRIPE_COVER_SESSION_HEALTH_ENABLE = env.bool(
    "STRIPE_COVER_SESSION_HEALTH_ENABLE", default=False
)

# Mailchimp
MAILCHIMP_ENABLED = env.bool("MAILCHIMP_ENABLED", default=False)
MAILCHIMP_CONFIG = {
    "MAILCHIMP_API_KEY": env("MAILCHIMP_API_KEY", default=None),
    "MAILCHIMP_PREFIX_SERVER": env("MAILCHIMP_PREFIX_SERVER", default=None),
    "MAILCHIMP_LIST_ID": env("MAILCHIMP_LIST_ID", default=None),
}
if MAILCHIMP_ENABLED is True:
    for _key in MAILCHIMP_CONFIG.keys():
        if MAILCHIMP_CONFIG.get(_key) is None:
            raise ValueError(f"{_key} is required")

# app version
APP_VERSION = env("APP_VERSION", default="v1.0.0")

TEAM_NAME = env("TEAM_NAME", default="Development")

APP_NAME = env("APP_NAME", default="Application")
