# Generated by Django 3.1.14 on 2023-03-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_clientdashboardwidget_dashboardconfig_widgetconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customreport',
            name='type',
            field=models.CharField(blank=True, choices=[('Analysis', 'Export Custom Analysis'), ('ShippingInvoice', 'Export Custom Shipping Invoices'), ('ShippingInvoiceTrans', 'Export Custom Shipping Invoice Transactions'), ('ShippingInvoiceTransUnmatched', 'Export Custom Shipping Invoice Unmatched'), ('Items', 'Export Custom Items')], default='Analysis', max_length=200, null=True),
        ),
    ]
