# Generated by Django 3.1.14 on 2023-04-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20230321_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='ac_cart_rover',
            field=models.JSONField(default=dict),
        ),
    ]
