# Generated by Django 3.1.14 on 2023-04-12 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_clientsettings_ac_cart_rover'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='ac_client_register',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClientCartRoverSetting',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('api_user', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal')),
            ],
            options={
                'unique_together': {('client', 'api_user', 'api_key')},
            },
        ),
    ]
