# Generated by Django 3.1.14 on 2023-04-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_auto_20230412_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customreport',
            name='bulk_operations',
            field=models.JSONField(default=dict),
        ),
    ]
