# Generated by Django 3.1.14 on 2023-05-11 03:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_auto_20230425_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReportCost',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_sales', models.IntegerField()),
                ('total_30d_sales', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal')),
            ],
            options={
                'unique_together': {('client', 'date')},
            },
        ),
    ]
