# Generated by Django 3.1.14 on 2023-06-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_auto_20230524_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
