# Generated by Django 3.1.14 on 2023-07-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_auto_20230627_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informedmarketplace',
            options={},
        ),
    ]
