# Generated by Django 3.1.14 on 2023-08-10 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0010_auto_20230725_0403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientReportCost',
        ),
    ]
