# Generated by Django 3.1.14 on 2023-08-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0011_delete_clientreportcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='actual_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True, verbose_name='Actual Shipping Cost'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='estimated_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True, verbose_name='Estimated Shipping Cost'),
        ),
        migrations.AddField(
            model_name='saleitemfinancial',
            name='actual_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True, verbose_name='Actual Shipping Cost'),
        ),
        migrations.AddField(
            model_name='saleitemfinancial',
            name='estimated_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True, verbose_name='Estimated Shipping Cost'),
        ),
    ]
