# Generated by Django 3.1.14 on 2023-11-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_auto_20230829_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcartroversetting',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='ac_3pl_central_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skuvaultprimetrack',
            name='source',
            field=models.CharField(choices=[('SKUVaultSource', 'SKU Vault'), ('CartRoverSource', 'Cart Rover'), ('3PLCentral', '3PL Central')], default='SKUVaultSource', max_length=50),
        ),
    ]
