# Generated by Django 3.1.14 on 2024-01-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_auto_20231123_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='is_it_department',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='it_department_orders_limit',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='ac_cart_rover',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
