# Generated by Django 3.1.14 on 2024-01-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_auto_20240108_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastatus',
            name='is_checking_prime',
            field=models.BooleanField(default=False),
        ),
    ]
