# Generated by Django 3.1.14 on 2024-02-19 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_datastatus_is_checking_prime'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsetting',
            name='est_unit_inbound_freight_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Est. Unit Inbound Freight Cost'),
        ),
        migrations.AddField(
            model_name='brandsetting',
            name='est_unit_outbound_freight_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Est. Unit Outbound Freight Cost'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='inbound_freight_cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True, verbose_name='Inbound Freight Cost'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='inbound_freight_cost_accuracy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='outbound_freight_cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True, verbose_name='Outbound Freight Cost'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='outbound_freight_cost_accuracy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='saleitemfinancial',
            name='inbound_freight_cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True, verbose_name='Inbound Freight Cost'),
        ),
        migrations.AddField(
            model_name='saleitemfinancial',
            name='inbound_freight_cost_accuracy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='saleitemfinancial',
            name='outbound_freight_cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True, verbose_name='Outbound Freight Cost'),
        ),
        migrations.AddField(
            model_name='saleitemfinancial',
            name='outbound_freight_cost_accuracy',
            field=models.IntegerField(null=True),
        ),
    ]
