# Generated by Django 3.1.14 on 2024-02-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0016_auto_20240219_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsetting',
            name='est_unit_inbound_freight_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Est. Unit Inbound Freight Cost'),
        ),
        migrations.AlterField(
            model_name='brandsetting',
            name='est_unit_outbound_freight_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Est. Unit Outbound Freight Cost'),
        ),
    ]
