# Generated by Django 3.1.14 on 2024-04-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0017_auto_20240222_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='is_remove_cogs_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
