# Generated by Django 3.1.14 on 2024-05-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0018_clientsettings_is_remove_cogs_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='parent_asin',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Style No.'),
        ),
        migrations.AddField(
            model_name='saleitemfinancial',
            name='parent_asin',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleitemfinancial',
            name='product_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleitemfinancial',
            name='product_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Style No.'),
        ),
    ]
