# Generated by Django 3.1.14 on 2024-06-14 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0019_auto_20240529_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentManage',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='dataflattentrack',
            name='type',
            field=models.CharField(choices=[('SALE_ITEMS', 'View Sale Items'), ('SALE_FINANCIAL', 'Sale Financial Item'), ('YOY_MONTHLY_SALE', 'YOY Monthly Sales'), ('YOY_30_DAY_SALE', 'YOY 30 Day Sales'), ('SALE_BY_DOLLAR', 'Sale By Dollar'), ('SALE_BY_UNIT', 'Sale By Unit'), ('ADVERTISING', 'Advertising'), ('SALE_BIG_MOVES', 'Sale Big Moves'), ('SALE_COMPARISION', 'All Sale Comparision'), ('PRODUCT_SALE', 'Ordered Product Sales'), ('FF_MONTHLY_SALE', 'Fulfillment Monthly Sales'), ('BRAND_30_DAY_SALE', 'Brand 30 Day Sales')], default='SALE_ITEMS', max_length=100),
        ),
        migrations.CreateModel(
            name='DivisionClientUserWidget',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.segmentmanage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.user')),
            ],
            options={
                'unique_together': {('client', 'user', 'segment')},
            },
        ),
    ]
