# Generated by Django 3.1.14 on 2024-07-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0020_auto_20240614_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataflattentrack',
            name='type',
            field=models.CharField(choices=[('SALE_ITEMS', 'View Sale Items'), ('SALE_FINANCIAL', 'Sale Financial Item'), ('YOY_MONTHLY_SALE', 'YOY Monthly Sales'), ('YOY_30_DAY_SALE', 'YOY 30 Day Sales'), ('SALE_BY_DOLLAR', 'Sale By Dollar'), ('SALE_BY_UNIT', 'Sale By Unit'), ('ADVERTISING', 'Advertising'), ('SALE_BIG_MOVES', 'Sale Big Moves'), ('SALE_COMPARISION', 'All Sale Comparision'), ('PROD_COMPARISON', 'All Sale Product Comparison'), ('PRODT_COMPARISON', 'All Sale Product Type Comparison'), ('PASIN_COMPARISON', 'All Sale Parent ASIN Comparison'), ('PRODUCT_SALE', 'Ordered Product Sales'), ('FF_MONTHLY_SALE', 'Fulfillment Monthly Sales'), ('BRAND_30_DAY_SALE', 'Brand 30 Day Sales')], default='SALE_ITEMS', max_length=100),
        ),
    ]
