# Generated by Django 3.1.14 on 2024-08-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0021_auto_20240705_0210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DivisionClientUserWidget',
            new_name='SegmentClientUserWidget',
        ),
        migrations.AddField(
            model_name='segmentmanage',
            name='category',
            field=models.CharField(choices=[('division', 'Division'), ('overall-sales', 'Overall Sales')], default='division', max_length=255),
        ),
    ]
