# Generated by Django 3.1.14 on 2024-08-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0022_auto_20240826_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsetting',
            name='add_user_provided_method',
            field=models.CharField(choices=[('Cost', 'Cost'), ('Percent', 'Percent')], default='Cost', max_length=100),
        ),
    ]
