# Generated by Django 3.1.14 on 2024-08-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0023_brandsetting_add_user_provided_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentmanage',
            name='category',
            field=models.CharField(choices=[('divisions', 'Divisions'), ('overall-sales', 'Overall Sales')], default='divisions', max_length=255),
        ),
    ]
