# Generated by Django 3.1.14 on 2024-08-28 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0024_auto_20240827_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='parent_asin',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='product_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Product Number'),
        ),
        migrations.AddField(
            model_name='item',
            name='product_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='brandsetting',
            name='add_user_provided_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Add. User-Provided'),
        ),
        migrations.AlterField(
            model_name='brandsetting',
            name='add_user_provided_method',
            field=models.CharField(choices=[('Cost', 'Cost'), ('Percent', 'Percent')], default='Cost', max_length=100, verbose_name='Add. User-Provided Method'),
        ),
        migrations.AlterField(
            model_name='brandsetting',
            name='po_dropship_cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PO Dropship'),
        ),
        migrations.AlterField(
            model_name='brandsetting',
            name='po_dropship_method',
            field=models.CharField(choices=[('Cost', 'Cost'), ('Percent', 'Percent')], default='Cost', max_length=100, verbose_name='PO Dropship Method'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Product Number'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='saleitemfinancial',
            name='product_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Product Number'),
        ),
        migrations.AlterField(
            model_name='saleitemfinancial',
            name='product_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Product Type'),
        ),
    ]
