# Generated by Django 3.1.14 on 2024-09-05 09:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0025_auto_20240828_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionClientUserWidget',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('divisions', 'Divisions'), ('overall-sales', 'Overall Sales')], default='divisions', max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_option', models.CharField(choices=[('Manual', 'Manual'), ('Historical', 'Historical')], default='Manual', max_length=255)),
                ('mtd_target_manual', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('mtd_max_manual', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('ytd_target_manual', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('ytd_max_manual', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('enabled', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.user')),
            ],
            options={
                'unique_together': {('client', 'user', 'category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='DivisionManage',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('divisions', 'Divisions'), ('overall-sales', 'Overall Sales')], default='divisions', max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('category', 'key')},
            },
        ),
        migrations.AddField(
            model_name='financialsettings',
            name='division_max_limit',
            field=models.IntegerField(default=5, verbose_name='Division max limit'),
        ),
        migrations.DeleteModel(
            name='SegmentClientUserWidget',
        ),
        migrations.DeleteModel(
            name='SegmentManage',
        ),
    ]
