# Generated by Django 3.1.14 on 2024-09-09 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0026_auto_20240905_0944'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='divisionclientuserwidget',
            unique_together={('client', 'category', 'key')},
        ),
        migrations.RemoveField(
            model_name='divisionclientuserwidget',
            name='user',
        ),
    ]
