# Generated by Django 3.1.14 on 2024-10-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0029_auto_20240918_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdashboardwidget',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientdashboardwidget',
            name='proportion',
            field=models.CharField(choices=[('Full', 'Full'), ('Half', 'Half'), ('Third', 'Third')], default='Full', max_length=255),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='proportion',
            field=models.CharField(choices=[('Full', 'Full'), ('Half', 'Half'), ('Third', 'Third')], default='Full', max_length=255),
        ),
    ]
