# Generated by Django 3.1.14 on 2024-10-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0030_auto_20241022_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdashboardwidget',
            name='position_default',
            field=models.IntegerField(default=0),
        ),
    ]
