# Generated by Django 3.1.14 on 2024-10-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0031_clientdashboardwidget_position_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdashboardwidget',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
