# Generated by Django 3.1.14 on 2024-11-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0033_auto_20241113_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionclientuserwidget',
            name='settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='divisionmanage',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
