# Generated by Django 3.1.14 on 2024-11-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0034_auto_20241115_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionclientuserwidget',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='divisionclientuserwidget',
            name='position_default',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='divisionmanage',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
