# Generated by Django 3.1.14 on 2025-03-17 07:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0036_auto_20241128_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customreport',
            name='type',
            field=models.CharField(blank=True, choices=[('Analysis', 'Export Custom Analysis'), ('ShippingInvoice', 'Export Custom Shipping Invoices'), ('ShippingInvoiceTrans', 'Export Custom Shipping Invoice Transactions'), ('ShippingInvoiceTransUnmatched', 'Export Custom Shipping Invoice Unmatched'), ('Items', 'Export Custom Items'), ('TopASINs', 'Export Custom TopASINs')], default='Analysis', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='TopClientASINs',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_asin', models.CharField(max_length=255)),
                ('child_asin', models.CharField(max_length=255)),
                ('segment', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.channel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal')),
            ],
            options={
                'unique_together': {('client', 'channel', 'child_asin', 'parent_asin')},
            },
        ),
    ]
