# Generated by Django 3.1.14 on 2025-04-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0038_auto_20250324_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='resync',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='saleitemfinancial',
            name='resync',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
