# Generated by Django 3.1.14 on 2025-04-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0039_auto_20250411_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='label_cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='label_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleitemfinancial',
            name='label_cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='saleitemfinancial',
            name='label_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
