# Generated by Django 3.1.14 on 2025-04-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0040_auto_20250422_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataflattentrack',
            name='batch_size',
            field=models.IntegerField(default=1000),
        ),
    ]
