# Generated by Django 3.1.14 on 2025-05-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0042_auto_20250512_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='ac_spapi_app_id',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
