# Generated by Django 3.1.14 on 2025-05-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0043_clientsettings_ac_spapi_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataflattentrack',
            name='last_rows_synced',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dataflattentrack',
            name='batch_size',
            field=models.IntegerField(default=1000, verbose_name='Per Batch Sync'),
        ),
    ]
