# Generated by Django 3.1.14 on 2025-06-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0044_auto_20250521_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='cog_extensiv_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='cog_priority_source',
            field=models.CharField(blank=True, choices=[('extensiv', 'Extensiv'), ('data_central', 'Data_Central'), ('item', 'Item')], help_text='Required if both Extensiv and DC and Item are enabled', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='cog_use_dc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='cog_use_extensiv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='cog_use_item',
            field=models.BooleanField(default=True),
        ),
    ]
