# Generated by Django 3.1.14 on 2025-06-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0045_auto_20250618_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cog_source',
            field=models.CharField(blank=True, choices=[('Item', 'Item'), ('Data Center', 'Data Center'), ('Extensiv', 'Extensiv')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saleitemfinancial',
            name='cog_source',
            field=models.CharField(blank=True, choices=[('Item', 'Item'), ('Data Center', 'Data Center'), ('Extensiv', 'Extensiv')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='cog_priority_source',
            field=models.CharField(blank=True, choices=[('Extensiv', 'Extensiv'), ('Data Center', 'Data Center'), ('Item', 'Item')], help_text='Required if both Extensiv and DC and Item are enabled', max_length=20, null=True),
        ),
    ]
