# Generated by Django 3.1.14 on 2025-06-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0046_auto_20250625_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customreport',
            name='type',
            field=models.CharField(blank=True, choices=[('Analysis', 'Export Custom Analysis'), ('ShippingInvoice', 'Export Custom Shipping Invoices'), ('ShippingInvoiceTrans', 'Export Custom Shipping Invoice Transactions'), ('ShippingInvoiceTransUnmatched', 'Export Custom Shipping Invoice Unmatched'), ('Items', 'Export Custom Items'), ('TopASINs', 'Export Custom TopASINs'), ('COGSConflict', 'Export Custom COGS Conflicts')], default='Analysis', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='cog_source',
            field=models.CharField(blank=True, choices=[('Extensiv', 'Extensiv'), ('Data Center', 'Data Center'), ('Item', 'Item')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saleitemfinancial',
            name='cog_source',
            field=models.CharField(blank=True, choices=[('Extensiv', 'Extensiv'), ('Data Center', 'Data Center'), ('Item', 'Item')], default=None, max_length=100, null=True),
        ),
    ]
