# Generated by Django 3.1.14 on 2025-06-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0047_auto_20250627_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='used_cog_priority',
            field=models.BooleanField(default=None, null=True, verbose_name='Used COG Source Priority'),
        ),
        migrations.AddField(
            model_name='saleitemfinancial',
            name='used_cog_priority',
            field=models.BooleanField(default=None, null=True, verbose_name='Used COG Source Priority'),
        ),
    ]
