# Generated by Django 3.1.14 on 2025-07-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0048_auto_20250627_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('IMPORT_SALE_DATA', 'Import Sale Data'), ('IMPORT_SALE_ITEM_DATA', 'Import Sale Item Data'), ('DELETE_SALE_ITEM_DATA', 'Delete Sale Item Data'), ('BULK_DELETE_SALE_ITEM_DATA', 'Bulk Delete Sale Item Data'), ('EDIT_SALE_ITEM_DATA', 'Edit Sale Item Data'), ('BULK_EDIT_SALE_ITEM_DATA', 'Bulk Edit Sale Item Data'), ('BULK_SYNC_SALE_ITEM_DATA', 'Bulk Sync Sale Item Data'), ('IMPORT_ITEM_DATA', 'Import Item Data'), ('CREATE_ITEM_DATA', 'Create Item Data'), ('UPDATE_ITEM_DATA', 'Update Item Data'), ('BULK_UPDATE_ITEM_DATA', 'Bulk Update Item Data'), ('BULK_DELETE_ITEM_DATA', 'Bulk Delete Item Data'), (
                'SYNC_CLIENT_PORTAL', 'Sync Client Portal'), ('IMPORT_BRAND_SETTING_DATA', 'Import Brand Setting Data'), ('IMPORT_FEDEX_SHIPMENT_DATA', 'Import FedEx Shipment Data'), ('IMPORT_APP_EAGLE_PROFILE_DATA', 'Import App Eagle Profile Data'), ('REVERT_BULK_EDIT_SALE_ITEM_DATA', 'Revert Bulk Edit Sale Item Data'), ('BULK_CUSTOM_REPORT_DATA', 'Bulk Custom Report Data'), ('REVOKED_ACTION', 'Revoked Action'), ('CONNECTION_SP_ACCOUNT', 'Connection Selling Partner Account'), ('REVOKE_SP_ACCOUNT', 'Revoked Selling Partner Account'), ('UPDATE_COGS_SOURCE_SETTINGS', 'Update COGS Source Settings')], max_length=50),
        ),
    ]
