# Generated by Django 3.1.14 on 2025-07-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0049_auto_20250709_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsettings',
            old_name='cog_use_item',
            new_name='cog_use_pf',
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='cog_priority_source',
            field=models.CharField(blank=True, choices=[('Extensiv', 'Extensiv'), ('Data Central', 'Data Central'), (
                'PF', 'PF')], help_text='Required if both Extensiv and DC and Item are enabled', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='cog_source',
            field=models.CharField(blank=True, choices=[('Extensiv', 'Extensiv'), (
                'Data Central', 'Data Central'), ('PF', 'PF')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saleitemfinancial',
            name='cog_source',
            field=models.CharField(blank=True, choices=[('Extensiv', 'Extensiv'), (
                'Data Central', 'Data Central'), ('PF', 'PF')], default=None, max_length=100, null=True),
        ),
    ]
