# Generated by Django 3.1.14 on 2025-07-15 10:39

import app.extensiv.variables
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0050_auto_20250714_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsettings',
            name='cog_priority_source',
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='cog_priority_source',
            field=models.JSONField(
                blank=True,
                null=True,
                default=app.extensiv.variables.default_priority_sources,
                help_text='Defines the priority order of COGS sources',
            ),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='used_cog_priority',
            field=models.IntegerField(default=None, null=True, validators=[
                                      django.core.validators.MinValueValidator(1)], verbose_name='Used COG Source Priority'),
        ),
        migrations.AlterField(
            model_name='saleitemfinancial',
            name='used_cog_priority',
            field=models.IntegerField(default=None, null=True, validators=[
                                      django.core.validators.MinValueValidator(1)], verbose_name='Used COG Source Priority'),
        ),
    ]
