# Generated by Django 3.1.14 on 2025-10-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0051_auto_20250715_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_replacement_order',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='replaced_order_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Replaced Order Id'),
        ),
    ]
