# Generated by Django 3.1.14 on 2025-10-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0052_auto_20251020_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='ac_spapi_type_reconnect',
            field=models.CharField(choices=[('default', 'Default'), ('rotation_date_line', 'Rotation Dateline'), ('lwa_secret_key', 'LWA Secret Key')], default='default', max_length=20),
        ),
    ]
