# Generated by Django 5.1.4 on 2025-01-06 08:09

import django.db.models.manager
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('CUSTOM', 'Custom'), ('ADMIN', 'Admin default'), ('MANAGER', 'Manager default'), ('STAFF', 'Staff default')], default='CUSTOM', max_length=50)),
                ('name', models.CharField(max_length=100, null=True)),
                ('level', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('CLIENT', 'Client')], default='CLIENT', max_length=50)),
                ('object_id', models.UUIDField(null=True)),
                ('type_created', models.CharField(choices=[('USER', 'Created by user'), ('SYSTEM', 'Created by system')], default='USER', max_length=10)),
                ('module', models.CharField(default=None, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessRulePermission',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DENY', 'Deny'), ('ALLOW', 'Allow'), ('INHERIT', 'Inherit')], default='ALLOW', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('CUSTOM', 'Custom'), ('ADMIN', 'Admin default'), ('MANAGER', 'Manager default'), ('STAFF', 'Staff default')], default='CUSTOM', max_length=10)),
                ('name', models.CharField(max_length=100, null=True)),
                ('level', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('CLIENT', 'Client')], default='CLIENT', max_length=50)),
                ('object_id', models.UUIDField(null=True)),
                ('type_created', models.CharField(choices=[('USER', 'Created by user'), ('SYSTEM', 'Created by system')], default='CUSTOM', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomRoleAccessRule',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgClientCustomRoleUser',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('priority', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgClientUserPermission',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('module', models.CharField(choices=[('DC', 'Data Central'), ('DS', 'Data Source'), ('MAP', 'MAP Watcher'), ('MT', 'Matrix'), ('RA', 'Reporting Application'), ('PF', 'Precise Financial'), ('TR', '2D Transit'), ('SKUF', 'SKUFlex'), ('SA', 'System Admin')], default='DC', max_length=50)),
                ('module_name', models.CharField(default=None, max_length=100, null=True)),
                ('group', models.CharField(choices=[('SALE_GROUP', 'Sales'), ('COLUMN_SET_GROUP', 'Columns'), ('FILTER_GROUP', 'Filters'), ('VIEW_GROUP', 'Views'), ('PF_ADMIN_GROUP', 'Administration'), ('PF_ITEMS_GROUP', 'Items'), ('PF_BRAND_SETTING_GROUP', 'Brand Settings'), ('PF_OVERVIEW_DASHBOARD_GROUP', 'Overview Dashboard'), ('PF_AD_DASHBOARD_GROUP', 'Advertising Dashboard'), ('PF_FEDEX_GROUP', 'FedEx Shipment'), ('PF_REPRICING_GROUP', 'Repricing'), ('PF_CUSTOM_REPORT_GROUP', 'Custom Reports'), ('ASIN_GROUP', 'ASIN'), ('BRAND_GROUP', 'Brand'), ('DD_REPORT_GROUP', 'Demand Data Report'), ('PO_GROUP', 'Purchase Order'), ('PRODUCT_REVIEW_GROUP', 'Product Reviews'), ('PROFILE_GROUP', 'Profiles'), ('INVENTORY_GROUP', 'Inventory'), ('DC_ADMIN_GROUP', 'Administration'), ('DS_GROUP', 'Data Sources'), ('MW_REPORT_GROUP', 'Report'), ('MW_PRICE_GROUP', 'Price'), ('MW_SI_GROUP', 'Sellers & Investigations'), ('MW_DASHBOARD_GROUP', 'Dashboards'), ('MW_ADMIN_GROUP', 'Administration'), ('MW_SALE_ENFORCEMENT_GROUP', 'Sale Enforcement'), ('RA_DASHBOARD_GROUP', 'Dashboards'), ('RA_VIZ_GROUP', 'Visualizations'), ('OVERVIEW_GROUP', 'Overview'), ('CD_GROUP', 'Custom Dashboard'), ('MT_ADMIN_GROUP', 'Administration'), ('MT_SI_GROUP', 'Brand Integrity'), ('ADVERTISING_GROUP', 'Advertising Module'), ('GA_GROUP', 'Geographic Analysis'), ('TR_2D_BARCODE_GROUP', '2D BARCODE'), ('TR_FNSKU_GROUP', 'FNSKU'), ('TR_HISTORY_GROUP', 'History'), ('TR_SETTING_GROUP', 'Setting'), ('TR_SHIPMENT_PLAN_GROUP', 'Shipment Plan'), ('TR_EFFICIENT_REPORT_GROUP', 'Efficient Report'), ('TR_CUSTOM_SHIPMENT_GROUP', 'Custom Shipments'), ('TR_VENDOR_CENTRAL_GROUP', 'Vendor Central '), ('TR_SHIPPING_LABEL_GROUP', 'Shipping Label'), ('TR_SHIPPING_LABEL_HISTORY_GROUP', 'Shipping Label History'), ('SALE_ORDER_GROUP', 'Sales Orders'), ('SKUF_FT_GROUP', 'Fulfillment Teams'), ('SKUF_COLUMN_SET_GROUP', 'SKUFlex Columns'), ('SKUF_FILTER_GROUP', 'SKUFlex Filters'), ('SKUF_VIEW_GROUP', 'SKUFlex Views'), ('SKUF_ADMIN_GROUP', 'SKUF Administration'), ('SKUF_ITEMS_GROUP', 'SKUF Items'), ('SKUF_PRODUCT_GROUP', 'Products'), ('SKUF_INVENTORY_ITEM_GROUP', 'Inventory Items')], max_length=50)),
                ('key', models.CharField(choices=[('SALE_IMPORT', 'Import'), ('SALE_SINGLE_EDIT', 'Single Edit'), ('SALE_BULK_EDIT', 'Bulk Edit'), ('SALE_VIEW_ALL', 'View All'), ('SALE_VIEW_24H', 'View 24h'), ('SALE_SINGLE_DELETE', 'Single Delete'), ('SALE_BULK_DELETE', 'Bulk Delete'), ('SALE_VIEW_AUDIT_LOG', 'View Audit Log'), ('SALE_BULK_PROCESSING_VIEW', 'Bulk Processing View'), ('SALE_REPORT_VIEW_FILTER', 'View'), ('SALE_REPORT_CREATE_FILTER', 'Create'), ('SALE_REPORT_EDIT_FILTER', 'Edit'), ('SALE_REPORT_DELETE_FILTER', 'Delete'), ('SALE_REPORT_SHARE_FILTER', 'Share'), ('SALE_REPORT_VIEW_COLUMN', 'View'), ('SALE_REPORT_CREATE_COLUMN', 'Create'), ('SALE_REPORT_EDIT_COLUMN', 'Edit'), ('SALE_REPORT_DELETE_COLUMN', 'Delete'), ('SALE_REPORT_SHARE_COLUMN', 'Share'), ('SALE_REPORT_VIEW_ALL_REPORT', 'View All'), ('SALE_REPORT_CREATE_REPORT', 'Create'), ('SALE_REPORT_EDIT_REPORT', 'Edit'), ('SALE_REPORT_DELETE_REPORT', 'Delete'), ('SALE_REPORT_SHARE_REPORT', 'Share'), ('PF_ITEM_VIEW', 'View'), ('PF_ITEM_CREATE', 'Create'), ('PF_ITEM_EDIT', 'Edit'), ('PF_ITEM_BULK_EDIT', 'Bulk Edit'), ('PF_ITEM_DELETE', 'Delete'), ('PF_ITEM_BULK_DELETE', 'Bulk Delete'), ('PF_ITEM_IMPORT', 'Import'), ('ACTIVITY_VIEW', 'View Activity'), ('TOOLS_VIEW', 'View Tools'), ('SYNC_WORKSPACE', 'Sync WorkSpace'), ('GENERATE_DATASOURCE', 'Generate Data Source'), ('CLIENT_SETTINGS_VIEW', 'View Client Settings'), ('CLIENT_SETTINGS_CHANGE', 'Change Client Settings'), ('PF_BRAND_SETTING_VIEW', 'View'), ('PF_BRAND_SETTING_EDIT', 'Edit'), ('PF_BRAND_SETTING_DELETE', 'Delete'), ('PF_BRAND_SETTING_IMPORT', 'Import'), ('PF_BRAND_SETTING_UPDATE_SALES', 'Update Sales'), ('PF_BRAND_SETTING_UPDATE_ITEMS', 'Update Items'), ('PF_BRAND_SETTING_EXPORT', 'Export'), ('PF_OVERVIEW_DASHBOARD_MANAGEMENT', 'Management'), ('PF_AD_DASHBOARD_MANAGEMENT', 'Management'), ('PF_FEDEX_VIEW', 'View'), ('PF_FEDEX_IMPORT', 'Import'), ('PF_REPRICING_VIEW', 'View'), ('PF_REPRICING_EDIT', 'Edit'), ('PF_REPRICING_DELETE', 'Delete'), ('PF_CUSTOM_REPORT_VIEW', 'View'), ('PF_CUSTOM_REPORT_EXPORT', 'Export'), ('ds_man', 'Data Source Management'), ('ds_feed_man', 'Data Feed Management'), ('ds_feed_exe', 'Data Feed Execution'), ('dc_asin_view', 'View'), ('dc_asin_edit', 'Edit'), ('dc_asin_edit_bulk', 'Bulk Edit'), ('dc_asin_import', 'Import'), ('dc_brand_view', 'View'), ('dc_brand_export', 'Export'), ('dc_brand_edit', 'Bulk Edit'), ('dc_dd_report_view', 'View'), ('dc_dd_report_man', 'Management'), ('dc_po_view', 'View'), ('dc_po_man', 'Management'), ('dc_pr_view', 'View'), ('dc_inv_sellers_view', 'Seller View'), ('dc_inv_sellers_man', 'Seller Management'), ('dc_inv_summary_view', 'Summary View'), ('dc_profile_view', 'View'), ('dc_profile_man', 'Management'), ('dc_client_man', 'Client Management'), ('dc_settings_man', 'Setting Management'), ('dc_sys_monitor', 'System Monitor'), ('dc_tool_index_man', 'Indexing Tool'), ('ra_dash_man', 'Dashboard Management'), ('ra_dash_access_man', 'Dashboard Access Management'), ('ra_viz_man', 'Visualization Management'), ('ra_viz_access_man', 'Visualization Access Management'), ('BRAMAN', 'Management'), ('BRAEXE', 'Execution'), ('MAPMAN', 'Management'), ('GSMAPMAN', 'Google Shopping Management'), ('NOTIFI', 'MAP Price Update Notification'), ('WALMARTMAN', 'Walmart Management'), ('SIVIEW', 'View'), ('SIMAN', 'Management'), ('DASMAN', 'Management'), ('ADMINMAN', 'Management'), ('se_create', 'Create'), ('se_edit', 'Edit'), ('se_view', 'View'), ('se_delete', 'Delete'), ('se_send', 'Send'), ('mat_ov_view', 'View'), ('mat_ov_edit', 'Edit'), ('mat_setting_edit', 'Edit Settings'), ('mat_admin_generate_ds_edit', 'Generate Default Data Source'), ('mat_admin_generate_dashboard_edit', 'Generate Default Dashboard'), ('mat_am_view', 'View'), ('mat_am_edit', 'Edit'), ('mat_cd_view', 'View'), ('mat_cd_edit', 'Management'), ('mat_si_view', 'View'), ('mat_ga_view', 'View'), ('mat_ga_edit', 'Edit'), ('TR_2D_BARCODE_MANAGEMENT', 'Management'), ('TR_2D_BARCODE_VIEW', 'View'), ('TR_FNSKU_MANAGEMENT', 'Management'), ('TR_FNSKU_VIEW', 'View'), ('TR_HISTORY_VIEW', 'View'), ('TR_HISTORY_EXTRACT_DATA', 'Extract Data'), ('TR_SETTING_MANAGEMENT', 'Management'), ('TR_SHIPMENT_PLAN_MANAGEMENT_STATUS', 'Manage shipment status'), ('TR_SHIPMENT_BOX_DELETE', 'Delete shipment box'), ('TR_EFF_REPORT_MANAGEMENT', 'Management'), ('TR_CUSTOM_SHIPMENT_MANAGEMENT', 'Management'), ('TR_CUSTOM_SHIPMENT_BOX_DELETE', 'Delete custom shipment box'), ('TR_VENDOR_CENTRAL_MANAGEMENT', 'Management'), ('TR_SHIPPING_LABEL_MANAGEMENT', 'Management'), ('TR_SHIPPING_LABEL_HISTORY_MANAGEMENT', 'Management'), ('SALE_ORDER_IMPORT', 'Import'), ('SALE_ORDER_SINGLE_EDIT', 'Single Edit'), ('SALE_ORDER_BULK_EDIT', 'Bulk Edit'), ('SALE_ORDER_VIEW_ALL', 'View All'), ('SALE_ORDER_SINGLE_DELETE', 'Single Delete'), ('SALE_ORDER_BULK_DELETE', 'Bulk Delete'), ('SALE_ORDER_VIEW_AUDIT_LOG', 'View Audit Log'), ('SALE_ORDER_MARK_AS_FULFILLED', 'Mark as Fulfilled'), ('SALE_ORDER_MOVE_TO_FT', 'Move to FT'), ('SKUF_SALE_REPORT_VIEW_FILTER', 'View'), ('SKUF_SALE_REPORT_CREATE_FILTER', 'Create'), ('SKUF_SALE_REPORT_EDIT_FILTER', 'Edit'), ('SKUF_SALE_REPORT_DELETE_FILTER', 'Delete'), ('SKUF_SALE_REPORT_SHARE_FILTER', 'Share'), ('SKUF_FT_VIEW_ALL', 'View All'), ('SKUF_FT_IMPORT', 'Import'), ('SKUF_FT_SINGLE_EDIT', 'Single Edit'), ('SKUF_PRODUCT_VIEW_ALL', 'View All'), ('SKUF_PRODUCT_IMPORT', 'Import'), ('SKUF_PRODUCT_SINGLE_EDIT', 'Single Edit'), ('SKUF_INVENTORY_ITEM_VIEW_ALL', 'View All'), ('SKUF_INVENTORY_ITEM_IMPORT', 'Import'), ('SKUF_INVENTORY_ITEM_SINGLE_EDIT', 'Single Edit'), ('SKUF_SALE_REPORT_VIEW_COLUMN', 'View'), ('SKUF_SALE_REPORT_CREATE_COLUMN', 'Create'), ('SKUF_SALE_REPORT_EDIT_COLUMN', 'Edit'), ('SKUF_SALE_REPORT_DELETE_COLUMN', 'Delete'), ('SKUF_SALE_REPORT_SHARE_COLUMN', 'Share'), ('SKUF_SALE_VIEW_VIEW_ALL_REPORT', 'View All'), ('SKUF_SALE_VIEW_CREATE_REPORT', 'Create'), ('SKUF_SALE_VIEW_EDIT_REPORT', 'Edit'), ('SKUF_SALE_VIEW_DELETE_REPORT', 'Delete'), ('SKUF_SALE_VIEW_SHARE_REPORT', 'Share'), ('SKUF_ITEM_VIEW', 'View'), ('SKUF_ITEM_CREATE', 'Create'), ('SKUF_ITEM_EDIT', 'Edit'), ('SKUF_ITEM_BULK_EDIT', 'Bulk Edit'), ('SKUF_ITEM_DELETE', 'Delete'), ('SKUF_ITEM_BULK_DELETE', 'Bulk Delete'), ('SKUF_ITEM_IMPORT', 'Import'), ('SKUF_ACTIVITY_VIEW', 'View Activity'), ('SKUF_TOOLS_VIEW', 'View Tools'), ('SKUF_SYNC_WORKSPACE', 'Sync WorkSpace'), ('SKUF_GENERATE_DATASOURCE', 'Generate Data Source'), ('SKUF_CLIENT_SETTINGS_VIEW', 'View Client Settings'), ('SKUF_CLIENT_SETTINGS_CHANGE', 'Change Client Settings')], max_length=50)),
                ('name', models.CharField(default='', max_length=100)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OverridingOrgClientUserPermission',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DENY', 'Deny'), ('ALLOW', 'Allow'), ('INHERIT', 'Inherit')], default='ALLOW', max_length=10)),
                ('object_id', models.UUIDField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('SALE_IMPORT', 'Import'), ('SALE_SINGLE_EDIT', 'Single Edit'), ('SALE_BULK_EDIT', 'Bulk Edit'), ('SALE_VIEW_ALL', 'View All'), ('SALE_VIEW_24H', 'View 24h'), ('SALE_SINGLE_DELETE', 'Single Delete'), ('SALE_BULK_DELETE', 'Bulk Delete'), ('SALE_VIEW_AUDIT_LOG', 'View Audit Log'), ('SALE_BULK_PROCESSING_VIEW', 'Bulk Processing View'), ('SALE_REPORT_VIEW_FILTER', 'View'), ('SALE_REPORT_CREATE_FILTER', 'Create'), ('SALE_REPORT_EDIT_FILTER', 'Edit'), ('SALE_REPORT_DELETE_FILTER', 'Delete'), ('SALE_REPORT_SHARE_FILTER', 'Share'), ('SALE_REPORT_VIEW_COLUMN', 'View'), ('SALE_REPORT_CREATE_COLUMN', 'Create'), ('SALE_REPORT_EDIT_COLUMN', 'Edit'), ('SALE_REPORT_DELETE_COLUMN', 'Delete'), ('SALE_REPORT_SHARE_COLUMN', 'Share'), ('SALE_REPORT_VIEW_ALL_REPORT', 'View All'), ('SALE_REPORT_CREATE_REPORT', 'Create'), ('SALE_REPORT_EDIT_REPORT', 'Edit'), ('SALE_REPORT_DELETE_REPORT', 'Delete'), ('SALE_REPORT_SHARE_REPORT', 'Share'), ('PF_ITEM_VIEW', 'View'), ('PF_ITEM_CREATE', 'Create'), ('PF_ITEM_EDIT', 'Edit'), ('PF_ITEM_BULK_EDIT', 'Bulk Edit'), ('PF_ITEM_DELETE', 'Delete'), ('PF_ITEM_BULK_DELETE', 'Bulk Delete'), ('PF_ITEM_IMPORT', 'Import'), ('ACTIVITY_VIEW', 'View Activity'), ('TOOLS_VIEW', 'View Tools'), ('SYNC_WORKSPACE', 'Sync WorkSpace'), ('GENERATE_DATASOURCE', 'Generate Data Source'), ('CLIENT_SETTINGS_VIEW', 'View Client Settings'), ('CLIENT_SETTINGS_CHANGE', 'Change Client Settings'), ('PF_BRAND_SETTING_VIEW', 'View'), ('PF_BRAND_SETTING_EDIT', 'Edit'), ('PF_BRAND_SETTING_DELETE', 'Delete'), ('PF_BRAND_SETTING_IMPORT', 'Import'), ('PF_BRAND_SETTING_UPDATE_SALES', 'Update Sales'), ('PF_BRAND_SETTING_UPDATE_ITEMS', 'Update Items'), ('PF_BRAND_SETTING_EXPORT', 'Export'), ('PF_OVERVIEW_DASHBOARD_MANAGEMENT', 'Management'), ('PF_AD_DASHBOARD_MANAGEMENT', 'Management'), ('PF_FEDEX_VIEW', 'View'), ('PF_FEDEX_IMPORT', 'Import'), ('PF_REPRICING_VIEW', 'View'), ('PF_REPRICING_EDIT', 'Edit'), ('PF_REPRICING_DELETE', 'Delete'), ('PF_CUSTOM_REPORT_VIEW', 'View'), ('PF_CUSTOM_REPORT_EXPORT', 'Export'), ('ds_man', 'Data Source Management'), ('ds_feed_man', 'Data Feed Management'), ('ds_feed_exe', 'Data Feed Execution'), ('dc_asin_view', 'View'), ('dc_asin_edit', 'Edit'), ('dc_asin_edit_bulk', 'Bulk Edit'), ('dc_asin_import', 'Import'), ('dc_brand_view', 'View'), ('dc_brand_export', 'Export'), ('dc_brand_edit', 'Bulk Edit'), ('dc_dd_report_view', 'View'), ('dc_dd_report_man', 'Management'), ('dc_po_view', 'View'), ('dc_po_man', 'Management'), ('dc_pr_view', 'View'), ('dc_inv_sellers_view', 'Seller View'), ('dc_inv_sellers_man', 'Seller Management'), ('dc_inv_summary_view', 'Summary View'), ('dc_profile_view', 'View'), ('dc_profile_man', 'Management'), ('dc_client_man', 'Client Management'), ('dc_settings_man', 'Setting Management'), ('dc_sys_monitor', 'System Monitor'), ('dc_tool_index_man', 'Indexing Tool'), ('ra_dash_man', 'Dashboard Management'), ('ra_dash_access_man', 'Dashboard Access Management'), ('ra_viz_man', 'Visualization Management'), ('ra_viz_access_man', 'Visualization Access Management'), ('BRAMAN', 'Management'), ('BRAEXE', 'Execution'), ('MAPMAN', 'Management'), ('GSMAPMAN', 'Google Shopping Management'), ('NOTIFI', 'MAP Price Update Notification'), ('WALMARTMAN', 'Walmart Management'), ('SIVIEW', 'View'), ('SIMAN', 'Management'), ('DASMAN', 'Management'), ('ADMINMAN', 'Management'), ('se_create', 'Create'), ('se_edit', 'Edit'), ('se_view', 'View'), ('se_delete', 'Delete'), ('se_send', 'Send'), ('mat_ov_view', 'View'), ('mat_ov_edit', 'Edit'), ('mat_setting_edit', 'Edit Settings'), ('mat_admin_generate_ds_edit', 'Generate Default Data Source'), ('mat_admin_generate_dashboard_edit', 'Generate Default Dashboard'), ('mat_am_view', 'View'), ('mat_am_edit', 'Edit'), ('mat_cd_view', 'View'), ('mat_cd_edit', 'Management'), ('mat_si_view', 'View'), ('mat_ga_view', 'View'), ('mat_ga_edit', 'Edit'), ('TR_2D_BARCODE_MANAGEMENT', 'Management'), ('TR_2D_BARCODE_VIEW', 'View'), ('TR_FNSKU_MANAGEMENT', 'Management'), ('TR_FNSKU_VIEW', 'View'), ('TR_HISTORY_VIEW', 'View'), ('TR_HISTORY_EXTRACT_DATA', 'Extract Data'), ('TR_SETTING_MANAGEMENT', 'Management'), ('TR_SHIPMENT_PLAN_MANAGEMENT_STATUS', 'Manage shipment status'), ('TR_SHIPMENT_BOX_DELETE', 'Delete shipment box'), ('TR_EFF_REPORT_MANAGEMENT', 'Management'), ('TR_CUSTOM_SHIPMENT_MANAGEMENT', 'Management'), ('TR_CUSTOM_SHIPMENT_BOX_DELETE', 'Delete custom shipment box'), ('TR_VENDOR_CENTRAL_MANAGEMENT', 'Management'), ('TR_SHIPPING_LABEL_MANAGEMENT', 'Management'), ('TR_SHIPPING_LABEL_HISTORY_MANAGEMENT', 'Management'), ('SALE_ORDER_IMPORT', 'Import'), ('SALE_ORDER_SINGLE_EDIT', 'Single Edit'), ('SALE_ORDER_BULK_EDIT', 'Bulk Edit'), ('SALE_ORDER_VIEW_ALL', 'View All'), ('SALE_ORDER_SINGLE_DELETE', 'Single Delete'), ('SALE_ORDER_BULK_DELETE', 'Bulk Delete'), ('SALE_ORDER_VIEW_AUDIT_LOG', 'View Audit Log'), ('SALE_ORDER_MARK_AS_FULFILLED', 'Mark as Fulfilled'), ('SALE_ORDER_MOVE_TO_FT', 'Move to FT'), ('SKUF_SALE_REPORT_VIEW_FILTER', 'View'), ('SKUF_SALE_REPORT_CREATE_FILTER', 'Create'), ('SKUF_SALE_REPORT_EDIT_FILTER', 'Edit'), ('SKUF_SALE_REPORT_DELETE_FILTER', 'Delete'), ('SKUF_SALE_REPORT_SHARE_FILTER', 'Share'), ('SKUF_FT_VIEW_ALL', 'View All'), ('SKUF_FT_IMPORT', 'Import'), ('SKUF_FT_SINGLE_EDIT', 'Single Edit'), ('SKUF_PRODUCT_VIEW_ALL', 'View All'), ('SKUF_PRODUCT_IMPORT', 'Import'), ('SKUF_PRODUCT_SINGLE_EDIT', 'Single Edit'), ('SKUF_INVENTORY_ITEM_VIEW_ALL', 'View All'), ('SKUF_INVENTORY_ITEM_IMPORT', 'Import'), ('SKUF_INVENTORY_ITEM_SINGLE_EDIT', 'Single Edit'), ('SKUF_SALE_REPORT_VIEW_COLUMN', 'View'), ('SKUF_SALE_REPORT_CREATE_COLUMN', 'Create'), ('SKUF_SALE_REPORT_EDIT_COLUMN', 'Edit'), ('SKUF_SALE_REPORT_DELETE_COLUMN', 'Delete'), ('SKUF_SALE_REPORT_SHARE_COLUMN', 'Share'), ('SKUF_SALE_VIEW_VIEW_ALL_REPORT', 'View All'), ('SKUF_SALE_VIEW_CREATE_REPORT', 'Create'), ('SKUF_SALE_VIEW_EDIT_REPORT', 'Edit'), ('SKUF_SALE_VIEW_DELETE_REPORT', 'Delete'), ('SKUF_SALE_VIEW_SHARE_REPORT', 'Share'), ('SKUF_ITEM_VIEW', 'View'), ('SKUF_ITEM_CREATE', 'Create'), ('SKUF_ITEM_EDIT', 'Edit'), ('SKUF_ITEM_BULK_EDIT', 'Bulk Edit'), ('SKUF_ITEM_DELETE', 'Delete'), ('SKUF_ITEM_BULK_DELETE', 'Bulk Delete'), ('SKUF_ITEM_IMPORT', 'Import'), ('SKUF_ACTIVITY_VIEW', 'View Activity'), ('SKUF_TOOLS_VIEW', 'View Tools'), ('SKUF_SYNC_WORKSPACE', 'Sync WorkSpace'), ('SKUF_GENERATE_DATASOURCE', 'Generate Data Source'), ('SKUF_CLIENT_SETTINGS_VIEW', 'View Client Settings'), ('SKUF_CLIENT_SETTINGS_CHANGE', 'Change Client Settings')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('module', models.CharField(choices=[('DC', 'Data Central'), ('DS', 'Data Source'), ('MAP', 'MAP Watcher'), ('MT', 'Matrix'), ('RA', 'Reporting Application'), ('PF', 'Precise Financial'), ('TR', '2D Transit'), ('SKUF', 'SKUFlex'), ('SA', 'System Admin')], default='DC', max_length=50)),
                ('module_name', models.CharField(default=None, max_length=100, null=True)),
                ('group', models.CharField(choices=[('SALE_GROUP', 'Sales'), ('COLUMN_SET_GROUP', 'Columns'), ('FILTER_GROUP', 'Filters'), ('VIEW_GROUP', 'Views'), ('PF_ADMIN_GROUP', 'Administration'), ('PF_ITEMS_GROUP', 'Items'), ('PF_BRAND_SETTING_GROUP', 'Brand Settings'), ('PF_OVERVIEW_DASHBOARD_GROUP', 'Overview Dashboard'), ('PF_AD_DASHBOARD_GROUP', 'Advertising Dashboard'), ('PF_FEDEX_GROUP', 'FedEx Shipment'), ('PF_REPRICING_GROUP', 'Repricing'), ('PF_CUSTOM_REPORT_GROUP', 'Custom Reports'), ('ASIN_GROUP', 'ASIN'), ('BRAND_GROUP', 'Brand'), ('DD_REPORT_GROUP', 'Demand Data Report'), ('PO_GROUP', 'Purchase Order'), ('PRODUCT_REVIEW_GROUP', 'Product Reviews'), ('PROFILE_GROUP', 'Profiles'), ('INVENTORY_GROUP', 'Inventory'), ('DC_ADMIN_GROUP', 'Administration'), ('DS_GROUP', 'Data Sources'), ('MW_REPORT_GROUP', 'Report'), ('MW_PRICE_GROUP', 'Price'), ('MW_SI_GROUP', 'Sellers & Investigations'), ('MW_DASHBOARD_GROUP', 'Dashboards'), ('MW_ADMIN_GROUP', 'Administration'), ('MW_SALE_ENFORCEMENT_GROUP', 'Sale Enforcement'), ('RA_DASHBOARD_GROUP', 'Dashboards'), ('RA_VIZ_GROUP', 'Visualizations'), ('OVERVIEW_GROUP', 'Overview'), ('CD_GROUP', 'Custom Dashboard'), ('MT_ADMIN_GROUP', 'Administration'), ('MT_SI_GROUP', 'Brand Integrity'), ('ADVERTISING_GROUP', 'Advertising Module'), ('GA_GROUP', 'Geographic Analysis'), ('TR_2D_BARCODE_GROUP', '2D BARCODE'), ('TR_FNSKU_GROUP', 'FNSKU'), ('TR_HISTORY_GROUP', 'History'), ('TR_SETTING_GROUP', 'Setting'), ('TR_SHIPMENT_PLAN_GROUP', 'Shipment Plan'), ('TR_EFFICIENT_REPORT_GROUP', 'Efficient Report'), ('TR_CUSTOM_SHIPMENT_GROUP', 'Custom Shipments'), ('TR_VENDOR_CENTRAL_GROUP', 'Vendor Central '), ('TR_SHIPPING_LABEL_GROUP', 'Shipping Label'), ('TR_SHIPPING_LABEL_HISTORY_GROUP', 'Shipping Label History'), ('SALE_ORDER_GROUP', 'Sales Orders'), ('SKUF_FT_GROUP', 'Fulfillment Teams'), ('SKUF_COLUMN_SET_GROUP', 'SKUFlex Columns'), ('SKUF_FILTER_GROUP', 'SKUFlex Filters'), ('SKUF_VIEW_GROUP', 'SKUFlex Views'), ('SKUF_ADMIN_GROUP', 'SKUF Administration'), ('SKUF_ITEMS_GROUP', 'SKUF Items'), ('SKUF_PRODUCT_GROUP', 'Products'), ('SKUF_INVENTORY_ITEM_GROUP', 'Inventory Items')], max_length=50)),
                ('group_name', models.CharField(default=None, max_length=100, null=True)),
                ('level', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('CLIENT', 'Client')], default='CLIENT', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
