# Generated by Django 5.1.4 on 2025-01-06 08:09

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('permission', '0001_initial'),
        ('tenancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUserProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tenancies.userclient',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUserProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tenancies.organizationuser',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='accessrule',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_client_access_rule_fk', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='accessrule',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessrulepermission',
            name='access_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission.accessrule'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_client_custom_role_fk', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customroleaccessrule',
            name='access_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission.accessrule'),
        ),
        migrations.AddField(
            model_name='customroleaccessrule',
            name='custom_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission.customrole'),
        ),
        migrations.AddField(
            model_name='orgclientcustomroleuser',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_client_user_custom_role_fk', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='orgclientcustomroleuser',
            name='custom_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission.customrole'),
        ),
        migrations.AddField(
            model_name='orgclientuserpermission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_client_user_permission_fk', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='overridingorgclientuserpermission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='overridingorgclientuserpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission.permission'),
        ),
        migrations.AddField(
            model_name='accessrulepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission.permission'),
        ),
    ]
