# Generated by Django 5.1.4 on 2025-01-06 08:09

import datetime
import django.utils.timezone
import django_better_admin_arrayfield.models.fields
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LWACredentialClientSetting',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(blank=None, default=None, max_length=100, null=True)),
                ('app_id', models.CharField(max_length=100, unique=True)),
                ('lwa_client_id', models.CharField(max_length=256)),
                ('lwa_secret_key_encrypted', models.TextField(verbose_name='lwa secret key(encrypted)')),
                ('is_active', models.BooleanField(default=True)),
                ('date_expired', models.DateTimeField(verbose_name='Rotation Deadline')),
                ('days_scheduled_notification', models.DurationField(default=datetime.timedelta(days=7))),
                ('emails', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.EmailField(max_length=254), default=list, size=None)),
                ('url_callbacks', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), default=list, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
