# Generated by Django 5.1.4 on 2025-05-23 02:23

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingURLCallback',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DONE', 'Done'), ('OPEN', 'Open'), ('ERROR', 'Error')], default='OPEN', max_length=100)),
                ('url', models.URLField(max_length=250)),
                ('retry', models.SmallIntegerField(default=0)),
                ('log', models.TextField(blank=True, null=True)),
                ('lwa_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_lwa_client_setting', to='app_setting.lwacredentialclientsetting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
