# Generated by Django 3.1.14 on 2023-07-21 10:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20230622_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjobclient',
            name='is_run_validations',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='communityjobclient',
            name='is_run_validations',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='datasourcecalculationjobclient',
            name='is_run_validations',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='importjobclient',
            name='is_run_validations',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='jobconfig',
            name='is_run_validations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobconfig',
            name='validations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, unique=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='sellingpartnerjobclient',
            name='is_run_validations',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='statsreportjobclient',
            name='is_run_validations',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='syncanalysisjobclient',
            name='is_run_validations',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='syncdatasourcejobclient',
            name='is_run_validations',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='timecontroljobclient',
            name='is_run_validations',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
