# Generated by Django 3.1.14 on 2025-06-25 10:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0046_auto_20250625_1709'),
        ('job', '0003_auto_20230721_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobconfig',
            name='category',
            field=models.CharField(choices=[('COMMUNITY', 'Community'), ('IMPORT', 'Import'), ('BULK', 'Bulk'), ('SYNC_ANALYSIS', 'Sync Analysis'), ('TIME_CONTROL', 'Time Control'), ('SYNC_DATA_SOURCE', 'Sync Data Source'), ('DATA_SOURCE_CALCULATION', 'Data Source Calculation'), ('SELLING_PARTNER', 'Selling Partner'), ('STATS_REPORT', 'Stats Reports'), ('COGS_MAPPING', 'COGS Mapping')], default='COMMUNITY', max_length=255),
        ),
        migrations.AlterField(
            model_name='taskrouteconfig',
            name='category',
            field=models.CharField(choices=[('COMMUNITY', 'Community'), ('IMPORT', 'Import'), ('BULK', 'Bulk'), ('SYNC_ANALYSIS', 'Sync Analysis'), ('TIME_CONTROL', 'Time Control'), ('SYNC_DATA_SOURCE', 'Sync Data Source'), ('DATA_SOURCE_CALCULATION', 'Data Source Calculation'), ('SELLING_PARTNER', 'Selling Partner'), ('STATS_REPORT', 'Stats Reports'), ('COGS_MAPPING', 'COGS Mapping')], default='COMMUNITY', max_length=255),
        ),
        migrations.CreateModel(
            name='COGSMappingJobClient',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('group_id', models.UUIDField(blank=True, default=None, null=True)),
                ('mode_run', models.CharField(choices=[('parallel', 'Parallel'), ('immediately', 'Immediately'), ('sequentially', 'Sequentially')], default='sequentially', max_length=200)),
                ('job_name', models.CharField(max_length=200)),
                ('module', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=200)),
                ('meta', models.JSONField(default=dict)),
                ('validations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, unique=True), blank=True, default=list, size=None)),
                ('is_run_validations', models.BooleanField(default=None, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('REVOKED', 'REVOKED'), ('REJECTED', 'REJECTED'), ('RETRY', 'RETRY'), ('IGNORED', 'IGNORED')], default='PENDING', max_length=200)),
                ('msg', models.TextField(default=None, null=True)),
                ('priority', models.IntegerField(default=None, null=True)),
                ('time_limit', models.IntegerField(default=None, null=True, verbose_name='Time limit (seconds)')),
                ('retry', models.BooleanField(default=False, verbose_name='Retry connection')),
                ('retry_policy', models.JSONField(blank=True, default=None, null=True, verbose_name='Retry policy connection')),
                ('recursive', models.IntegerField(default=0)),
                ('max_recursive', models.IntegerField(default=0)),
                ('callback', models.JSONField(default=dict)),
                ('queue', models.CharField(default=None, max_length=255, null=True)),
                ('exchange', models.CharField(default=None, max_length=255, null=True)),
                ('routing_key', models.CharField(default=None, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='cogsmappingjobclient',
            index=models.Index(fields=['client', 'status'], name='job_cogsmap_client__1ab1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='cogsmappingjobclient',
            index=models.Index(fields=['client', 'status', 'modified'], name='job_cogsmap_client__b6836b_idx'),
        ),
        migrations.AddIndex(
            model_name='cogsmappingjobclient',
            index=models.Index(fields=['client', 'status', 'modified', 'group_id'], name='job_cogsmap_client__996625_idx'),
        ),
        migrations.AddIndex(
            model_name='cogsmappingjobclient',
            index=models.Index(fields=['client', 'status', 'created', 'recursive'], name='job_cogsmap_client__7ac2da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cogsmappingjobclient',
            unique_together={('id', 'name', 'client', 'module', 'method', 'created')},
        ),
    ]
