"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import datetime
import os
import sys
from datetime import timedelta
import environ
import psycopg2
from Crypto.PublicKey import RSA

from app import __version__

#
env = environ.Env()
env.read_env()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT_DIR = environ.Path(__file__) - 3

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

#  Environment
ENVIRONMENT = env('ENVIRONMENT')

ALLOWED_HOSTS = []

# Application definition

DJANGO_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'revproxy',
    # 'django_filters',
)

THIRD_PARTY_APPS = (
    'rest_framework',
    'rest_framework.authtoken',
    'oauth2_provider',
    'rest_auth',
    'django.contrib.sites',
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    'rest_auth.registration',
    'drf_yasg',
    'corsheaders',
    'django_celery_beat',
    'django_celery_results',
    'auditlog',
    'plat_import_lib_api',
    'rangefilter',
    'django_better_admin_arrayfield',
)

# Apps specific for this project go here.
LOCAL_APPS = (
    'app.core.apps.CoreConfig',
    'app.financial.apps.FinancialConfig',
    'app.edi.apps.EdiConfig',
    'app.database.apps.DatabaseConfig',
    'app.job.apps.JobConfig',
    'app.es.apps.EsConfig',
    'app.selling_partner.apps.SellingPartnerConfig',
    'app.shopify_partner.apps.ShopifyPartnerConfig',
    'app.stat_report.apps.StatReportConfig',
    'app.third_party_logistic.apps.ThirdPartyLogisticConfig',
    'app.csp.apps.CPSConfig',
    'app.extensiv.apps.ExtensivConfig',
)

SITE_ID = 1

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

BUGSNAG = {
    "api_key": env('BUGSNAG_API_KEY'),
    "params_filters": [
        "password",
        "password_confirmation",
        "authorization",
        "aws_",
        "database",
        "redis",
    ],
    "release_stage": ENVIRONMENT,
    "notify_release_stages": ['production', 'development', 'qa', 'uat'],
    "app_version": __version__
}

MIDDLEWARE = [
    # 'bugsnag.django.middleware.BugsnagMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'app.csp.middleware.CSPMiddleware'
]

AUTHENTICATION_BACKENDS = (
    'oauth2_provider.backends.OAuth2Backend',
    # Uncomment following if you want to access the admin
    'django.contrib.auth.backends.ModelBackend'
)

# Auth model
# AUTH_USER_MODEL = 'tenancies.User'

# Route
ROOT_URLCONF = 'config.urls'

# Templates
TEMPLATES_ROOT = str(ROOT_DIR('templates'))
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_ROOT],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    {
        "BACKEND": "django.template.backends.jinja2.Jinja2",
        "DIRS": [TEMPLATES_ROOT],
        "APP_DIRS": True,
        "OPTIONS": {
            "environment": "app.csp.tests.environment.environment",
            "extensions": ["app.csp.extensions.NoncedScript"],
        },
    }
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
DATABASE_URL = env.str('DATABASE_URL')

DATABASES = {
    'default': env.db('DATABASE_URL', default='postgres:///goldfish'),
}

DATABASES['default']['ATOMIC_REQUESTS'] = True
DB_NAME_RUNNING_TEST = env('DB_NAME_RUNNING_TEST', default='financial_unit_test')
DATABASES['default']['TEST'] = {'NAME': DB_NAME_RUNNING_TEST}

TESTING = sys.argv[1] == "test"

if not TESTING:

    databases_config = []
    try:
        sql = """
              SELECT *
              FROM database_databaseconfig
              WHERE database_databaseconfig.name != 'default'
              ORDER BY database_databaseconfig.created ASC; \
              """
        conn = psycopg2.connect(DATABASE_URL)
        cur = conn.cursor()
        cur.execute(sql)
        columns = [col[0] for col in cur.description]
        databases_config = [dict(zip(columns, row)) for row in cur.fetchall()]
        cur.close()
        conn.close()
        #
        for config in databases_config:
            DATABASES.update({config['name']: env.db(f"DATABASE_{config['name'].upper()}_URL", config['url'])})
            DATABASES[config['name']]['ATOMIC_REQUESTS'] = True
            DATABASES[config['name']]['TEST'] = {'NAME': DB_NAME_RUNNING_TEST}
    except Exception as ex:
        # print(f"[settings][databases_config] {ex}")
        pass

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

# STATIC FILE CONFIGURATION
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = str(ROOT_DIR('staticfiles'))

# See: https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = '/static/'

REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        # 'rest_framework.authentication.TokenAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework_jwt.authentication.JSONWebTokenAuthentication'
        'app.core.simple_authentication.JWTTokenHandlerAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': [],
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',  # LimitOffsetPagination
    'DEFAULT_PAGINATION_CLASS': 'app.core.pagination.StandardResultsSetPagination',  # LimitOffsetPagination
    'PAGE_SIZE': env.int("PAGE_SIZE", 20),
    'PAGINATE_BY_PARAM': 'page_size',  # Allow client to override, using `?page_size=xxx`.
    'MAX_PAGINATE_BY': 500,  # Maximum limit allowed when using `?page_size=xxx`.
    # 'DATE_INPUT_FORMATS': ['YYYY-MM-DD HH:MM:SS'],
    'EXCEPTION_HANDLER': 'app.core.exception_handler.api_exception_handler',
}

OLD_PASSWORD_FIELD_ENABLED = True

ACCOUNT_EMAIL_REQUIRED = True

ACCOUNT_EMAIL_VERIFICATION = "mandatory"

# Allow CORS requests from all domain
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = False

CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-ps-client-id'
)

#  Celery
BROKER_URL = env('CELERY_BROKER_URL', default='django://')
CELERYD_MAX_TASKS_PER_CHILD = 100
CELERYD_TASK_SOFT_TIME_LIMIT = 2400  # 40 minutes
CELERY_RESULT_BACKEND = 'django-db'
CELERY_TASK_TRACK_STARTED = True
CELERY_IGNORE_RESULT = False
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# default queue name
# for default worker
CELERY_TASK_DEFAULT_QUEUE = env.str('CELERY_TASK_DEFAULT_QUEUE', default='celery')
CELERY_TASK_QUEUE_IMPORT_LIB = env.str('CELERY_TASK_QUEUE_IMPORT_LIB', default=CELERY_TASK_DEFAULT_QUEUE)
#
CELERY_TASK_ROUTES = {
    # import lib
    'plat_import_lib_api.tasks.*': {'queue': CELERY_TASK_QUEUE_IMPORT_LIB}
    # TODO: classify live feed tasks
}

#  Redis
USER_CLIENT_REDIS_CHANNEL = env('USER_CLIENT_REDIS_CHANNEL', default='redis://redis:6379/0')
REDIS_TTL = env.int('REDIS_TTL', 5)
USER_CLIENT_REDIS_ENABLED = env.bool('USER_CLIENT_REDIS_ENABLED', default=False)
PREFIX_REDIS_KEY = env.str('PREFIX_REDIS_KEY', default='PF')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': USER_CLIENT_REDIS_CHANNEL,
        'TIMEOUT': int(REDIS_TTL * 60),
        'KEY_PREFIX': PREFIX_REDIS_KEY,  # add prefix handler clean key in redis
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Firebase
USER_CLIENT_FIRE_BASE_ENABLED = env.bool('USER_CLIENT_FIRE_BASE_ENABLED', default=False)
FIRE_BASE_REAL_TIME_DB_URL = env('FIRE_BASE_REAL_TIME_DB_URL')
FIRE_BASE_ACCESS_KEY = env('FIRE_BASE_ACCESS_KEY')
FIRE_BASE_REF = env('FIRE_BASE_REF', default='/')

#  Email Config
EMAIL_BACKEND = env('EMAIL_BACKEND')
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_USE_TLS = env('EMAIL_USE_TLS')
DJANGO_DEFAULT_FROM_EMAIL = env('DJANGO_DEFAULT_FROM_EMAIL')

#  Swagger
SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'api_key': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}

#  JWT`
PRIVATE_KEY_PATH = env('PRIVATE_KEY_PATH')
PUBLIC_KEY_PATH = env('PUBLIC_KEY_PATH')
#  get the current dir of *.pem
f = open(str(ROOT_DIR) + str(PRIVATE_KEY_PATH), 'r')
JWT_PRIVATE_KEY = RSA.import_key(f.read())
f.close()
f = open(str(ROOT_DIR) + str(PUBLIC_KEY_PATH), 'r')
JWT_PUBLIC_KEY = RSA.import_key(f.read())
f.close()

JWT_EXPIRATION_DELTA = env.int('JWT_EXPIRATION_DELTA', default=5)  # minutes
JWT_AUDIENCE = env.str("JWT_AUDIENCE", default="portal")

JWT_AUTH = {
    'JWT_PRIVATE_KEY': JWT_PRIVATE_KEY.export_key(),
    'JWT_PUBLIC_KEY': JWT_PUBLIC_KEY.export_key(),
    'JWT_ALGORITHM': 'RS256',
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_ALLOW_REFRESH': True,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=60 * int(JWT_EXPIRATION_DELTA)),
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),
    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
}

# Simple JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(seconds=60 * int(JWT_EXPIRATION_DELTA)),
    "REFRESH_TOKEN_LIFETIME": datetime.timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "RS256",
    "SIGNING_KEY": JWT_PRIVATE_KEY.export_key(),
    "VERIFYING_KEY": JWT_PUBLIC_KEY.export_key(),
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": None,
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": None,

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

#  Google Cloud Storage
GOOGLE_CLOUD_STORAGE_BUCKET_NAME = env('GOOGLE_CLOUD_STORAGE_BUCKET_NAME')
GOOGLE_CLOUD_STORAGE_BUCKET_ACCESS_KEY = env('GOOGLE_CLOUD_STORAGE_BUCKET_ACCESS_KEY')

# BASE URL
BASE_URL = env("BASE_URL", default="http://localhost:8000")

# Media
MEDIA_ROOT = str(ROOT_DIR("media"))
MEDIA_URL = env("MEDIA_URL", default="/media/")

# logging

BASE_LOG_DIR = os.environ.get('BASE_LOG_DIR', default='logs')
LOG_FILE_PATH = os.path.join(BASE_LOG_DIR, 'logs.log')

# List of upload handler classes to be applied in order.
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s '
                      '%(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s\t%(asctime)s\t%(filename)s\t%(lineno)d\t%(message)s'
        },
    },
    'root': {
        'level': env.str('DJANGO_LOG_LEVEL', default="INFO"),
        'handlers': ['bugsnag', 'console', 'file'],
    },
    'handlers': {
        # Send info messages to file
        'file': {
            'level': env.str('DJANGO_LOG_LEVEL', default="INFO"),
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOG_FILE_PATH,
            'when': 'D',
            'encoding': 'utf-8',
            'formatter': 'simple',
        },
        # Send messages to console
        'console': {
            'level': env.str('DJANGO_CONSOLE_LOG_LEVEL', default="INFO"),
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        #  critical errors are logged to bugsnag
        'bugsnag': {
            'level': 'ERROR',
            'class': 'bugsnag.handlers.BugsnagHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    }
}

# App Version
APP_VERSION = env('APP_VERSION', default='v1.0.0')

# PS URL
URL_PORTAL_SERVICE = env.str('URL_PORTAL_SERVICE', default='http://portal-api.qa.channelprecision.com')

# DS URL
URL_DS_SERVICE = env.str('URL_DS_SERVICE', default='http://ds-api.qa.channelprecision.com')
DS_TOKEN = env.str('DS_TOKEN')

# AC URL
URL_AC_SERVICE = env.str('URL_AC_SERVICE', default='http://ac-api.qa.channelprecision.com')
AC_API_KEY = env.str('AC_API_KEY')
AC_SERVICE_LIMIT_ITEM = env.int('AC_SERVICE_LIMIT_ITEM', 50)

# DC URL
URL_DC_SERVICE = env.str('URL_DC_SERVICE')
DC_SERVICE_LIMIT_ITEM = env.int('DC_SERVICE_LIMIT_ITEM', 50)

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# using queue for import file
# PLAT_IMPORT_USE_QUEUE = env.bool('PLAT_IMPORT_USE_QUEUE', default=False)
# PLAT_IMPORT_DATA_CHUNK_SIZE = env.int('PLAT_IMPORT_DATA_CHUNK_SIZE', default=2000)
# PLAT_IMPORT_STORAGE = env.str('PLAT_IMPORT_STORAGE', default='local')
# PLAT_IMPORT_ROUND_UP = env.float('PLAT_IMPORT_ROUND_UP', default=0.01)
# PLAT_IMPORT_STORAGE_FOLDER = env.str('PLAT_IMPORT_STORAGE_FOLDER', default='pf/lib_imports')
# # Define location load module import define
# IMPORT_MODULE_TEMPLATE = env.str('IMPORT_MODULE_TEMPLATE', default='app.financial.import_template.base')
# CELERY_APP_CONFIG = env.str('CELERY_APP_CONFIG', default='app.core.celery')

# Local folder for exported data_flatten
DATA_FLATTEN_EXPORT_FOLDER = env.str('DATA_FLATTEN_EXPORT_FOLDER', default='data_flatten_export')
# Data feed cloud storage folder
DATA_FEED_STORAGE_FOLDER = env.str('DATA_FEED_STORAGE_FOLDER', default='pf/data_feeds')

# Internal token for calling from other service
INTERNAL_TOKEN = env.str('INTERNAL_TOKEN', default='150f4ed3-5515-492e-84f9-09ca0acf8652')
PS_INTERNAL_TOKEN = env.str('PS_INTERNAL_TOKEN', default='123456')

DAY_RANGE_FEDEX_SHIPMENT = env.int('DAY_RANGE_FEDEX_SHIPMENT', 2)

# DS_EXPORT_LIMIT
DS_EXPORT_LIMIT = env.str('DS_EXPORT_LIMIT', default='150000')

# DS TimeZone Calculate
DS_TZ_CALCULATE = env.str('DS_TZ_CALCULATE', default="America/Los_Angeles")

# config FTP Fedex
FTP_FEDEX_HOST = env.str('FTP_FEDEX_HOST', default=None)
FTP_FEDEX_USER = env.str('FTP_FEDEX_USER', default=None)
FTP_FEDEX_PASSWD = env.str('FTP_FEDEX_PASSWD', default=None)
FTP_FEDEX_PORT = env.int('FTP_FEDEX_PORT', default=21)
FTP_FEDEX_DIR_PREFIX = env.str('FTP_FEDEX_DIR_PREFIX', default='')
FTP_FEDEX_DEBUG_LEVEL = env.int('FTP_FEDEX_DEBUG_LEVEL', default=0)

#
ELASTICSEARCH_URL_DEFAULT = env.str('ELASTICSEARCH_URL_DEFAULT', default='http://localhost:9200')

# twilio
TWILIO_ACCOUNT_SID = env.str('TWILIO_ACCOUNT_SID', default=None)
TWILIO_AUTH_TOKEN = env.str('TWILIO_AUTH_TOKEN', default=None)
TWILIO_PHONE_NUMBER = env.str('TWILIO_PHONE_NUMBER', default=None)
BASE_HOME_URL = env.str('BASE_HOME_URL', default='http://localhost:8080')

#
TINYURL_API_TOKEN = env.str('TINYURL_API_TOKEN', default=None)

#
FERNET_KEY = env.str('FERNET_KEY', default=None)

# Shopify, release version
SHOPIFY_API_VERSION = env.str('SHOPIFY_API_VERSION', default='2025-10')

CLIENT_ID_SHOPIFY_REVIEW = env.str('CLIENT_ID_SHOPIFY_REVIEW', default=None)
