# Generated by Django 3.1.14 on 2023-02-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0001_initial'),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseclientconfig',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal'),
        ),
        migrations.AddField(
            model_name='databaseclientconfig',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.databaseconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='databaseclientconfig',
            unique_together={('client', 'database')},
        ),
    ]
