import base64
import hashlib
import hmac

from app.core.logger import logger


def verify_webhook(data, hmac_header, api_secret_key: str) -> bool:
    """
    hmac header is generated by api secret key and data reqeust from Shopify

    compare generated hmac and hmac header from request
    """
    try:
        digest = hmac.new(api_secret_key.encode('utf-8'), data, digestmod=hashlib.sha256).digest()
        computed_hmac = base64.b64encode(digest)
        return hmac.compare_digest(computed_hmac, hmac_header.encode('utf-8'))
    except Exception as err:
        logger.error(f'[Shopify][verify_webhook] {err}')
        raise err
