# Generated by Django 3.1.14 on 2023-11-23 03:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0013_auto_20231123_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account3PLCentral',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_auth_id', models.CharField(max_length=50)),
                ('client_auth_secret', models.CharField(max_length=100)),
                ('user_login', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('synced', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal')),
            ],
            options={
                'unique_together': {('client', 'client_auth_id', 'user_login')},
            },
        ),
    ]
