from celery.states import PENDING, RECEIVED, STARTED, SUCCESS, FAILURE, REVOKED, REJECTED, RETRY, IGNORED

ROUTE_WORKER_STARTED_STATUS = 'STARTED'
ROUTE_WORKER_STOPPED_STATUS = 'STOPPED'

ROUTE_WORKER_STATUS = (
    (ROUTE_WORKER_STARTED_STATUS, ROUTE_WORKER_STARTED_STATUS),
    (ROUTE_WORKER_STOPPED_STATUS, ROUTE_WORKER_STOPPED_STATUS),
)

STATUS_CHOICE = (
    (PENDING, PENDING),
    (RECEIVED, RECEIVED),
    (STARTED, STARTED),
    (SUCCESS, SUCCESS),
    (FAILURE, FAILURE),
    (REVOKED, REVOKED),
    (REJECTED, REJECTED),
    (RETRY, RETRY),
    (IGNORED, IGNORED),
)

#
COMMUNITY_CATEGORY = 'COMMUNITY'
IMPORT_CATEGORY = 'IMPORT'
BULK_CATEGORY = 'BULK'
SYNC_ANALYSIS_CATEGORY = 'SYNC_ANALYSIS'
TIME_CONTROL_CATEGORY = 'TIME_CONTROL'
SYNC_DATA_SOURCE_CATEGORY = 'SYNC_DATA_SOURCE'
DATA_SOURCE_CALCULATION_CATEGORY = 'DATA_SOURCE_CALCULATION'
SELLING_PARTNER_CATEGORY = 'SELLING_PARTNER'
STATS_REPORT_CATEGORY = 'STATS_REPORT'
COGS_MAPPING_CATEGORY = 'COGS_MAPPING'

JOB_CATEGORY_CHOICES = (
    (COMMUNITY_CATEGORY, 'Community'),
    (IMPORT_CATEGORY, 'Import'),
    (BULK_CATEGORY, 'Bulk'),
    (SYNC_ANALYSIS_CATEGORY, 'Sync Analysis'),
    (TIME_CONTROL_CATEGORY, 'Time Control'),
    (SYNC_DATA_SOURCE_CATEGORY, 'Sync Data Source'),
    (DATA_SOURCE_CALCULATION_CATEGORY, 'Data Source Calculation'),
    (SELLING_PARTNER_CATEGORY, 'Selling Partner'),
    (STATS_REPORT_CATEGORY, 'Stats Reports'),
    (COGS_MAPPING_CATEGORY, 'COGS Mapping'),
)

LIST_JOB_CATEGORY = [item[0] for item in JOB_CATEGORY_CHOICES]
#
#
CELERY_NUMBER_WORKER = 2
CELERY_JOB_CONCURRENCY_WORKER = 20
CELERY_JOB_CONCURRENCY_TOTAL = CELERY_JOB_CONCURRENCY_WORKER * CELERY_NUMBER_WORKER

#
MODE_RUN_PARALLEL = "parallel"
MODE_RUN_IMMEDIATELY = "immediately"
MODE_RUN_SEQUENTIALLY = "sequentially"

MODE_RUN_CHOICE = (
    (MODE_RUN_PARALLEL, "Parallel"),
    (MODE_RUN_IMMEDIATELY, "Immediately"),
    (MODE_RUN_SEQUENTIALLY, "Sequentially"),
)
