# config for log type

LIVE_FEED_RECENT_POSTED_TODAY_TYPE = 'posted_today'
LIVE_FEED_RECENT_MODIFIED_TODAY_TYPE = 'modified_today'
LIVE_FEED_RECENT_REPLACEMENT_RECENT_TODAY_TYPE = 'replacement_modified_today'

LIVE_FEED_RECENT_TYPE_LIST = [LIVE_FEED_RECENT_POSTED_TODAY_TYPE, LIVE_FEED_RECENT_MODIFIED_TODAY_TYPE,
                              LIVE_FEED_RECENT_REPLACEMENT_RECENT_TODAY_TYPE]

MINUTE_RECENT_DATA_AC = 30

TIME_CONTROL_LOG_TYPE = 'TIME_CONTROL_LOG_TYPE'
FLATTEN_TRACK_LOG_TYPE = 'FLATTEN_TRACK_LOG_TYPE'

SALE_EVENT_TYPE = 'Sale'
FINANCIAL_EVENT_TYPE = 'FinancialEvent'
INFORMED_TYPE = 'Informed'

OPEN_STATUS = 'Open'
READY_STATUS = 'Ready'
PROCESS_STATUS = 'Process'
ERROR_STATUS = 'Error'
IGNORE_STATUS = 'Ignore'
DONE_STATUS = 'Done'

PF_TRUST_STATUS = (
    (OPEN_STATUS, OPEN_STATUS),
    (READY_STATUS, READY_STATUS),
    (PROCESS_STATUS, PROCESS_STATUS),
    (ERROR_STATUS, ERROR_STATUS),
    (IGNORE_STATUS, IGNORE_STATUS),
    (DONE_STATUS, DONE_STATUS)
)

PF_TRUST_TYPE = (
    (SALE_EVENT_TYPE, 'Sale'),
    (FINANCIAL_EVENT_TYPE, 'Financial Event'),
    (INFORMED_TYPE, 'Informed')
)

PF_TIME_CONTROL_PRIORITY_TYPE = {
    SALE_EVENT_TYPE: 1,
    FINANCIAL_EVENT_TYPE: 1,
    INFORMED_TYPE: 2
}

TIME_CONTROl_TYPE_LIST = [item[0] for item in PF_TRUST_TYPE]

TIME_CONTROL_NUMBER_BEAT_JOB = len(TIME_CONTROl_TYPE_LIST) * 2

MARKETPLACE_AMZ_TYPE = 'AMZ'
MARKETPLACE_SHOPIFY_TYPE = 'SHOPIFY'
