SPAPI_CONNECT_METHOD = 'spapi'
MWS_CONNECT_METHOD = 'mws'
SKUVAULT_CONNECT_METHOD = 'skuvault'
CART_ROVER_CONNECT_METHOD = 'cart-rover'
THIRD_PARTY_LOGISTIC_CONNECT_METHOD = '3pl-central'
SC_SHOPIFY_CONNECT = 'shopify'

SELLER_CENTRAL_INTEGRATION_ENUM = (
    (SPAPI_CONNECT_METHOD, 'SPAPI Connect'),
    (MWS_CONNECT_METHOD, 'MWS Keys'),
    (SKUVAULT_CONNECT_METHOD, 'SKUVault Account'),
    (CART_ROVER_CONNECT_METHOD, 'Cart Rover Account'),
    (SC_SHOPIFY_CONNECT, 'Shopify Connect'),
)
