# Generated by Django 3.1.14 on 2023-02-24 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthTokenRequest',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_url', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('access_token', models.TextField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=256)),
                ('secret', models.TextField(verbose_name='secret (encrypted)')),
                ('set_new_secret_key', models.BooleanField(default=True)),
                ('redirect_url_oauth', models.CharField(max_length=256)),
                ('scope', models.TextField()),
                ('web_redirect_url', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopifyPartnerOauthClientRegister',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal')),
                ('oauth_token_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_partner.oauthtokenrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='shopifypartneroauthclientregister',
            index=models.Index(fields=['client', 'oauth_token_request'], name='shopify_par_client__0887c0_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifypartneroauthclientregister',
            index=models.Index(fields=['client', 'enabled'], name='shopify_par_client__e75298_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopifypartneroauthclientregister',
            unique_together={('client', 'oauth_token_request')},
        ),
        migrations.AddIndex(
            model_name='oauthtokenrequest',
            index=models.Index(fields=['client', 'shop_url'], name='oauth_generate_url'),
        ),
        migrations.AddIndex(
            model_name='oauthtokenrequest',
            index=models.Index(fields=['state', 'shop_url'], name='callback_oauth'),
        ),
        migrations.AlterUniqueTogether(
            name='oauthtokenrequest',
            unique_together={('client', 'shop_url')},
        ),
    ]
