OPEN_STATUS_KEY = "OPEN"
DONE_STATUS_KEY = "DONE"
ERROR_STATUS_KEY = "ERROR"

LWA_CREDENTIAL_URL_STATUS = (
    (DONE_STATUS_KEY, "Done"),
    (OPEN_STATUS_KEY, "Open"),
    (ERROR_STATUS_KEY, "Error"),
)
