# Generated by Django 2.2.2 on 2021-07-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0013_asintest_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimporttemporary',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('validating', 'Validating'), ('validated', 'Validated'), ('processing', 'Processing'), ('processed', 'Processed'), ('failure', 'Failure'), ('revoked', 'Revoked'), ('reverting', 'Reverting'), ('reverted', 'Reverted')], default='uploading', max_length=20, verbose_name='status of file temp'),
        ),
    ]
