# Generated by Django 2.2.24 on 2022-03-04 10:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0015_auto_20210714_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_healthy', models.BooleanField(default=True)),
                ('message', models.TextField()),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(unique=True), blank=True, default=list, size=None)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='dataimporttemporary',
            index=models.Index(fields=['module', 'status'], name='module_status_idx'),
        ),
    ]
