# Generated by Django 2.2.24 on 2022-03-09 04:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0016_auto_20220304_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health',
            old_name='data',
            new_name='client_ids',
        ),
        migrations.AddField(
            model_name='health',
            name='import_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(unique=True), blank=True, default=list, size=None),
        ),
    ]
