# Generated by Django 2.2.24 on 2022-03-17 11:26

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('plat_import_lib_api', '0017_auto_20220309_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('use_queue', models.BooleanField(default=False)),
                ('bulk_process_size', models.IntegerField(default=2000)),
                ('storage_location', models.CharField(default='local', max_length=100)),
                ('storage_folder', models.CharField(default='plat/lib_imports', max_length=100)),
                ('round_up_currency', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('google_cloud_storage_bucket_name', models.CharField(default=None, max_length=200, null=True)),
                ('google_cloud_storage_bucket_access_key', models.CharField(default=None, max_length=200, null=True)),
                ('date_time_format', models.CharField(default='%Y-%m-%d %H:%M:%S', max_length=100)),
                ('module_template_location',
                 models.CharField(default='plat_import_lib_api.services.modules.base', max_length=200)),
                ('healthy_check_minute', models.IntegerField(default=30)),
                ('auto_clean_day', models.IntegerField(default=30)),
                ('module_reopen_exclude',
                 django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, unique=True),
                                                           blank=True, default=list, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='dataimporttemporary',
            options={'ordering': ['created']},
        ),
        migrations.CreateModel(
            name='RawDataTemporary',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.IntegerField(default=1)),
                ('status', models.CharField(
                    choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('validating', 'Validating'),
                             ('validated', 'Validated'), ('processing', 'Processing'), ('processed', 'Processed'),
                             ('failure', 'Failure'), ('revoked', 'Revoked'), ('reverting', 'Reverting'),
                             ('reverted', 'Reverted'), ('reporting', 'Reporting'), ('reported', 'Reported')],
                    default='uploaded', max_length=20)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('map_config', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('data_map_config', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('type', models.CharField(choices=[('created', 'created'), ('updated', 'updated')], default='created',
                                          max_length=50)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('validation_errors', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('processing_errors', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('hash_data', models.CharField(max_length=32)),
                ('lib_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 to='plat_import_lib_api.DataImportTemporary')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='rawdatatemporary',
            index=models.Index(fields=['lib_import', 'status'], name='plat_import_lib_imp_c4605e_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdatatemporary',
            index=models.Index(fields=['lib_import', 'hash_data'], name='plat_import_lib_imp_d29dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdatatemporary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='data_json_index',
                                                           opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='rawdatatemporary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data_map_config'],
                                                           name='data_map_config_json_index',
                                                           opclasses=['jsonb_path_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='rawdatatemporary',
            unique_together={('lib_import', 'hash_data')},
        ),
    ]
