# Generated by Django 2.2.24 on 2022-03-18 04:15

from django.db import migrations, transaction


def create_record_settings(apps, schema_editor):
    try:
        Setting = apps.get_model('plat_import_lib_api', 'Setting')
        find = Setting.objects.count() > 0
        if not find:
            Setting.objects.bulk_create([Setting(use_queue=False)])
    except Exception as ex:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('plat_import_lib_api', '0018_auto_20220317_1126'),
    ]

    operations = [
        migrations.RunPython(create_record_settings, reverse_code=migrations.RunPython.noop),
    ]
