# Generated by Django 2.2.24 on 2022-03-22 18:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0019_auto_20220318_0415'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rawdatatemporary',
            name='plat_import_lib_imp_d29dc7_idx',
        ),
        migrations.AddField(
            model_name='rawdatatemporary',
            name='key_map',
            field=models.TextField(default=None, null=True, verbose_name='Key mapping config'),
        ),
        migrations.AddField(
            model_name='rawdatatemporary',
            name='parent_key_map',
            field=models.TextField(default=None, null=True, verbose_name='Parent key mapping config'),
        ),
        migrations.AlterField(
            model_name='rawdatatemporary',
            name='processing_errors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='rawdatatemporary',
            name='validation_errors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='rawdatatemporary',
            index=models.Index(fields=['lib_import', 'key_map'], name='plat_import_lib_imp_ae9565_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdatatemporary',
            index=models.Index(fields=['lib_import', 'parent_key_map'], name='plat_import_lib_imp_03ff6a_idx'),
        ),
    ]
