# Generated by Django 2.2.24 on 2022-03-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0020_auto_20220322_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimporttemporary',
            name='file_url_cloud',
            field=models.TextField(default=None, null=True),
        ),
    ]
