# Generated by Django 2.2.24 on 2022-04-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0021_dataimporttemporary_file_url_cloud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatatemporary',
            name='is_complete',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rawdatatemporary',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
