# Generated by Django 2.2.24 on 2022-05-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0022_auto_20220405_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataimporttemporary',
            options={},
        ),
        migrations.AlterModelOptions(
            name='health',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rawdatatemporary',
            options={},
        ),
    ]
