# Generated by Django 2.2.24 on 2022-05-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0023_auto_20220504_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatatemporary',
            name='type',
            field=models.CharField(choices=[('created', 'created'), ('updated', 'updated'), ('ignored', 'ignored')], default='created', max_length=50),
        ),
    ]
