# Generated by Django 2.2.24 on 2022-05-25 07:03

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0024_auto_20220520_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimporttemporary',
            name='module_label',
            field=models.CharField(null=True, blank=True, default=None, max_length=100),
        ),
        migrations.AddIndex(
            model_name='dataimporttemporary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['meta'], name='meta_json_index', opclasses=['jsonb_path_ops']),
        ),
    ]
