# Generated by Django 2.2.24 on 2022-09-05 08:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0025_auto_20220525_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatatemporary',
            name='meta_addition',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
