# Generated by Django 2.2.24 on 2022-09-20 10:12

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0026_rawdatatemporary_meta_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimporttemporary',
            name='meta_hash',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='dataimporttemporary',
            index=models.Index(fields=['module', 'client_id', 'meta_hash', 'progress'], name='module_client_id_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='dataimporttemporary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['info_import_file'], name='info_import_file_json_index', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='rawdatatemporary',
            index=models.Index(fields=['lib_import', 'hash_data'], name='plat_import_lib_imp_d29dc7_idx'),
        ),
    ]
