# Generated by Django 3.1.14 on 2022-10-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0027_auto_20220920_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimporttemporary',
            name='info_import_file',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dataimporttemporary',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rawdatatemporary',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rawdatatemporary',
            name='data_map_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rawdatatemporary',
            name='map_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rawdatatemporary',
            name='meta_addition',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rawdatatemporary',
            name='processing_errors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='rawdatatemporary',
            name='validation_errors',
            field=models.JSONField(default=list),
        ),
    ]
