# Generated by Django 3.1.14 on 2025-04-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0028_auto_20221013_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatatemporary',
            name='type',
            field=models.CharField(choices=[('created', 'created'), ('updated', 'updated'), ('deleted', 'deleted'), ('ignored', 'ignored')], default='created', max_length=50),
        ),
    ]
