# Generated by Django 3.1.14 on 2023-02-24 09:16

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdiInvoiceSource',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('Import', 'Import'), ('FTP EDI', 'FTP EDI'), ('FTP CSV', 'FTP CSV')], default='FTP EDI', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Process', 'Process'), ('Done', 'Done'), ('Error', 'Error')], default='Pending', max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('log', models.TextField(default=None, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
