# Generated by Django 3.1.14 on 2023-02-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edi', '0001_initial'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ediinvoicesource',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.clientportal'),
        ),
        migrations.AddIndex(
            model_name='ediinvoicesource',
            index=models.Index(fields=['client', 'date', 'file_path', 'status'], name='edi_ediinvo_client__97d493_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ediinvoicesource',
            unique_together={('client', 'source', 'date', 'file_path')},
        ),
    ]
